### ISSUE TITLE
(JP) クラッシュリカバリ時にFATAL:  XX000: attempt to redefine parameter "pg_strom.enabled_global"

### ISSUE THREAD

**Issue by onlyindreams** [pg-strom/devel#105]
FATALエラーが発生してPostgreSQLのクラッシュリカバリが機能しません。

```
[nanzai@saba sepgsql]$ kill -9 32261
[nanzai@saba sepgsql]$ 2015-01-09 15:39:45 JST DB: PID:32257 LOG:  00000: background writer process (PID 32261) was terminated by signal 9: Killed
2015-01-09 15:39:45 JST DB: PID:32257 LOCATION:  LogChildExit, postmaster.c:3323
2015-01-09 15:39:45 JST DB: PID:32257 LOG:  00000: terminating any other active server processes
2015-01-09 15:39:45 JST DB: PID:32257 LOCATION:  HandleChildCrash, postmaster.c:3044
2015-01-09 15:39:45 JST DB: PID:32257 LOG:  00000: all server processes terminated; reinitializing
2015-01-09 15:39:45 JST DB: PID:32257 LOCATION:  PostmasterStateMachine, postmaster.c:3567
2015-01-09 15:39:46 JST DB: PID:32257 FATAL:  XX000: attempt to redefine parameter "pg_strom.enabled_global"
2015-01-09 15:39:46 JST DB: PID:32257 LOCATION:  define_custom_variable, guc.c:7204
```

pg_strom.enabled_globalパラメータは共有メモリ上に確保しているために、リカバリ時にbsearchで見つかってしまうのでエラーになってしまうようです。

**Comment by onlyindreams** [comment]
理解不足でした。クラッシュリカバリ時にDefineCustomBoolVariableを呼んでしまっているのが問題でした。
かといって、パラメータの共有化のために共有メモリを使用しているため、_PG_initには置けないということですね...どうしましょうか。。

**Comment by onlyindreams** [comment]
やっぱりGucContext=PGC_SIGHUPにして、reload形式にするしかないのかもしれません。

**Comment by kaigai** [comment]
ちょっと他のバグの方がヤバいので優先度は落とします。

**Comment by kaigai** [comment]
共有メモリの初期化コンテキストでGUCを設定しているのがマズかった模様。
cudaブランチ側ですが、
①_PG_init()でカスタムGUCを設定。assign/showフック付き。
    この時点では postgresql.conf の設定値を private 変数に保持。
②共有メモリを獲得。private 変数の内容を shared 変数にコピー。
③以降は assign / show フックが shared 変数を参照。

共有メモリ上に設定されていた値は再起動で保持されませんが、これは
そもそもそーゆーものですので構いません。

**Comment by onlyindreams** [comment]
すいません、前に聞いたことがあるかもしれませんが、
このパラメータはALTER SYSTEM + pg_reload_conf()ではダメなのでしょうか。

```
alter system set pg_strom.enabled to off;
select pg_reload_conf();
```

**Comment by kaigai** [comment]
普通のGUCと同じなので問題ないハズ。

一部のworkerプロセスで共有メモリをデタッチする人がいたので、それへの対応は
必要でしたが、共有メモリを使わないプロセスでPG-Stromが使用される事はないの
で、実用上問題にはならないでしょう。

**Comment by onlyindreams** [comment]
すいません、聞き方が悪かったです。

pg_strom.enabled_global パラメータは
pg_strom.enabledパラメータをALTER SYSTEMで変更するのと同じ効果なので、不要ではないか

ということです。

**Comment by kaigai** [comment]
ああ、なるほど。

厳密には同じでないみたいだけど、ユースケースを考えると
そっちの方が適切かもね。
（別のactive sessionのGUC設定内容を外から触りたいケースってのは、
アプリが張ったセッションで手出しできないって場合だろうから、普通は
デフォルト値が入っているので）

で、同じでないケースというのは、あるセッションで明示的に
```
postgres=# set pg_strom.enabled = off;
SET
```
されている状態で、別のセッションが
```
postgres=# alter system set pg_strom.enabled = on;
ALTER SYSTEM
postgres=# select pg_reload_conf();
 pg_reload_conf
----------------
 t
(1 row)
```

を実行したけども、一番目のセッションでは
```
postgres=# show pg_strom.enabled;
 pg_strom.enabled
------------------
 off
(1 row)
```
であるまま。

RESETかけると反映されるけどね。
```
postgres=# reset pg_strom.enabled;
RESET
postgres=# show pg_strom.enabled;
 pg_strom.enabled
------------------
 on
(1 row)
```
ProcessConfigFile()を詳しく読めば判るんじゃないかと思うけど、
pg_strom.enabledがローカルに何か値を設定されている場合には
SIGHUPだけではローカル設定を上書きするような動作にはなって
いなかった。

**Comment by onlyindreams** [comment]
不要かどうかの判断についてはお任せいたします。
cudaブランチをマスタに統合後、本現象が再現しないようであればクローズする予定です。

**Comment by kaigai** [comment]
pg_strom.enabled_global を削除しました。

FAQか何かに記載しておきましょう。
