### ISSUE TITLE
(JP) ビルド失敗　duplicate symbol _kparam_get_value in: 

### ISSUE THREAD

**Issue by acgacgacgacg** [pg-strom/devel#110]
sepgsqlのcustom-join branchを使っていますが、ビルドしたら、下記のエラーが出ました。

duplicate symbol _kparam_get_value in:
    src/main.o
    src/shmem.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/codegen.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/mqueue.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/restrack.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/grafter.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/datastore.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/gpuscan.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/gpuhashjoin.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/gpupreagg.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/opencl_entry.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/opencl_serv.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/opencl_devinfo.o
duplicate symbol _kparam_get_value in:
    src/main.o
    src/opencl_devprog.o
ld: 13 duplicate symbols for architecture x86_64

**Comment by kaigai** [comment]
AMDのOpenCLランタイム向け修正を加えた時のミスですね。

kparam_get_value() 関数はデバイス側だけでなくホスト側でも使用する関数なので
HOST_STATIC_INLINE　付きで定義する必要がありました。

6d2138f395fb3cb2109547b7b3c139ac9cc00f6d で修正しました。
