### ISSUE TITLE
ビルド時エラー

### ISSUE THREAD

**Issue by acgacgacgacg** [pg-strom/devel#113]
pg_stromとsepgsql両方のmasterを使いますが、ビルドすると下記のエラーが出ました。

Undefined symbols for architecture x86_64:
  "_create_plan_recurse", referenced from:
      _create_gpuhashjoin_plan in gpuhashjoin.o
  "_set_join_pathlist_hook", referenced from:
      _pgstrom_init_gpuhashjoin in gpuhashjoin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kaigai** [comment]
sepgsql側はcustom_joinブランチを使用してください。

CustomScan の JOIN 対応は現在コミュニティで議論している途中ですので、masterブランチには反映されていません。
