### ISSUE TITLE
(JP)ビルドじエラー：Undefined symbols

### ISSUE THREAD

**Issue by acgacgacgacg** [pg-strom/devel#114]
度々すみませんが、ご指摘のとおりcustom_joinを使い、pg_stromはmasterとcustom_join両方とも試してみましたが、同じ下記のエラーがでました。

Undefined symbols for architecture x86_64:
  "_create_plan_recurse", referenced from:
      _create_gpuhashjoin_plan in gpuhashjoin.o
ld: symbol(s) not found for architecture x86_64

**Comment by kaigai** [comment]
sepgsql 側の custom_join ブランチが少々古いようです。
git pullして最新版に更新してもらえますか？

create_plan_recurse() は後でstatic関数ではダメだと気が付き、
２、３週ほど前に更新した部分です。

**Comment by acgacgacgacg** [comment]
ご回答ありがとうございました。
sepgsqlのcustom_joinの最新バージョンは19日前更新の方でしょうか。
下記のurlからダウンロードしたんですが、
https://github.com/kaigai/sepgsql/tree/custom_join

**Comment by kaigai** [comment]
そうです。実際には ce67136984cdaf59d5c4ffbf5d223f02a8efcc10 の時点で create_plan_recurse がexternalに変わっているので、これ以降のバージョンという事になります。

**Comment by acgacgacgacg** [comment]
ビルドが成功しました。ありがとうございました。
