### ISSUE TITLE
Can't compile on mac

### ISSUE THREAD

**Issue by Paxa** [pg-strom/devel#116]
```
src/main.c:27:10: fatal error: 'utils/ruleutils.h' file not found
```

OS X 10.9

I think documentation is outdated, does it require to have cuda (or only opencl)? Can it run on amd and intel gpus?

**Comment by kaigai** [comment]
You need to use "custom_join" branch of https://github.com/kaigai/sepgsql

Because all custom-scan interface is not yet merged, we still need a few small enhancement to the vanilla PostgreSQL.

**Comment by kaigai** [comment]
> I think documentation is outdated, does it require to have cuda (or only opencl)? Can it run on amd and intel gpus?

At this moment, we stand on OpenCL; but only runtime provided by nvidia is validated.
However, we plan to back CUDA because of software quality issues.

**Comment by francoisp** [comment]
Just went through this, you need to donwload make and sudo make install postgres dev, this header is a new header that is not in 9.4.1

**Comment by francoisp** [comment]
I cloned you fork of postgres sepgsql and I'm still getting this:

src/gpuscan.c:360:9: error: no member named 'custom_relids' in
      'struct CustomScan'; did you mean 'custom_exprs'?
        cscan->custom_relids = bms_make_singleton(seqscan->scanrelid);

**Comment by kaigai** [comment]
We moved to CUDA, instead of OpenCL.
