### ISSUE TITLE
Unable to make pg-strom on ubuntu 14.04LTS with PSQL 9.5devel

### ISSUE THREAD

**Issue by jordanrinke** [pg-strom/devel#124]
I have 9.5devel installed, but attempting to make pg-strom fails:

On Ubuntu 14.04 LTS

root@testgpu:/opt/pg-strom# pg_config
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =
CC = gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lz -lreadline -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 9.5devel

and the make:

root@testgpu:/opt/pg-strom# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic  -I /usr/local/cuda/include -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o src/gpuhashjoin.o src/gpuhashjoin.c
src/gpuhashjoin.c:50:1: error: unknown type name ‘set_join_pathlist_hook_type’
 static set_join_pathlist_hook_type set_join_pathlist_next;
 ^
src/gpuhashjoin.c: In function ‘gpuhashjoin_add_join_path’:
src/gpuhashjoin.c:950:25: error: called object ‘set_join_pathlist_next’ is not a function or function pointer
   set_join_pathlist_next(root,
                         ^
src/gpuhashjoin.c:50:36: note: declared here
 static set_join_pathlist_hook_type set_join_pathlist_next;
                                    ^
In file included from /usr/local/pgsql/include/server/nodes/primnodes.h:21:0,
                 from /usr/local/pgsql/include/server/nodes/parsenodes.h:24,
                 from /usr/local/pgsql/include/server/nodes/makefuncs.h:17,
                 from src/gpuhashjoin.c:24:
src/gpuhashjoin.c: In function ‘gpuhashjoin_codegen_projection’:
src/gpuhashjoin.c:1175:23: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
  forthree (lc1, ghjoin->custom_ps_tlist,
                       ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:27: note: in definition of macro ‘forthree’
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                           ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:33: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                                 ^
src/gpuhashjoin.c:1175:2: note: in expansion of macro ‘forthree’
  forthree (lc1, ghjoin->custom_ps_tlist,
  ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:33: warning: value computed is not used [-Wunused-value]
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                                 ^
src/gpuhashjoin.c:1175:2: note: in expansion of macro ‘forthree’
  forthree (lc1, ghjoin->custom_ps_tlist,
  ^
src/gpuhashjoin.c:1223:24: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
   forthree (lc1, ghjoin->custom_ps_tlist,
                        ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:27: note: in definition of macro ‘forthree’
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                           ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:33: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                                 ^
src/gpuhashjoin.c:1223:3: note: in expansion of macro ‘forthree’
   forthree (lc1, ghjoin->custom_ps_tlist,
   ^
/usr/local/pgsql/include/server/nodes/pg_list.h:190:33: warning: value computed is not used [-Wunused-value]
  for ((cell1) = list_head(list1), (cell2) = list_head(list2), (cell3) = list_head(list3); \
                                 ^
src/gpuhashjoin.c:1223:3: note: in expansion of macro ‘forthree’
   forthree (lc1, ghjoin->custom_ps_tlist,
   ^
src/gpuhashjoin.c: In function ‘create_gpuhashjoin_plan’:
src/gpuhashjoin.c:1941:3: warning: implicit declaration of function ‘create_plan_recurse’ [-Wimplicit-function-declaration]
   Plan     *scan_plan = create_plan_recurse(root, scan_path);
   ^
src/gpuhashjoin.c:1941:25: warning: initialization makes pointer from integer without a cast [enabled by default]
   Plan     *scan_plan = create_plan_recurse(root, scan_path);
                         ^
src/gpuhashjoin.c:1956:8: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
   mhash->custom_ps_tlist = scan_plan->targetlist;
        ^
src/gpuhashjoin.c:2029:13: warning: assignment makes pointer from integer without a cast [enabled by default]
  outer_plan = create_plan_recurse(root, gpath->outer_path);
             ^
src/gpuhashjoin.c:2073:8: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
  ghjoin->custom_ps_tlist = build_pseudo_targetlist(gpath, &ghj_info, tlist);
        ^
src/gpuhashjoin.c:2090:23: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
         (Node *)ghjoin->custom_ps_tlist, true);
                       ^
src/gpuhashjoin.c: In function ‘gpuhashjoin_begin’:
src/gpuhashjoin.c:2300:38: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
  tupdesc = ExecCleanTypeFromTL(ghjoin->custom_ps_tlist, false);
                                      ^
src/gpuhashjoin.c: In function ‘gpuhashjoin_exec_bulk’:
src/gpuhashjoin.c:2840:25: warning: variable ‘pds’ set but not used [-Wunused-but-set-variable]
  pgstrom_data_store    *pds;
                         ^
src/gpuhashjoin.c: In function ‘gpuhashjoin_remap_raw_expression’:
src/gpuhashjoin.c:3106:26: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
  context.ps_tlist = cscan->custom_ps_tlist;
                          ^
In file included from /usr/local/pgsql/include/server/nodes/primnodes.h:21:0,
                 from /usr/local/pgsql/include/server/nodes/parsenodes.h:24,
                 from /usr/local/pgsql/include/server/nodes/makefuncs.h:17,
                 from src/gpuhashjoin.c:24:
src/gpuhashjoin.c: In function ‘gpuhashjoin_explain’:
src/gpuhashjoin.c:3136:22: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
   foreach (lc1, cscan->custom_ps_tlist)
                      ^
/usr/local/pgsql/include/server/nodes/pg_list.h:162:26: note: in definition of macro ‘foreach’
  for ((cell) = list_head(l); (cell) != NULL; (cell) = lnext(cell))
                          ^
src/gpuhashjoin.c:3142:30: error: ‘CustomScan’ has no member named ‘custom_ps_tlist’
    if (lc1 != list_head(cscan->custom_ps_tlist))
                              ^
src/gpuhashjoin.c: In function ‘pgstrom_init_gpuhashjoin’:
src/gpuhashjoin.c:3809:27: error: ‘set_join_pathlist_hook’ undeclared (first use in this function)
  set_join_pathlist_next = set_join_pathlist_hook;
                           ^
src/gpuhashjoin.c:3809:27: note: each undeclared identifier is reported only once for each function it appears in
make: *** [src/gpuhashjoin.o] Error 1
root@testgpu:/opt/pg-strom#

**Comment by kaigai** [comment]
Could you use "custom_join" branch of the following branch?
Custom-join interface (that allows to connect PG-Strom and PostgreSQL) is not committed
to PostgreSQL v9.5devel, so special patched version is needed.
```
https://github.com/kaigai/sepgsql/tree/custom_join
```

community proposition:
```
https://commitfest.postgresql.org/4/15/
```

**Comment by jordanrinke** [comment]
That got me up and running - I can't seem to create my shadow table though. I ran 'CREATE EXTENSION pg_strom;' which created the extension but it doesn't seem to have created the FDW of the SERVER. When trying to create the shadow table 
```
CREATE FOREIGN TABLE ftbl (
              a int,
              b int,
              t text,
              x float,
              y float
           ) SERVER pg_strom;
```
I get 
```
ERROR:  server "pg_strom" does not exist
```
although:
```
postgres=# \dx
                                  List of installed extensions
   Name   | Version |   Schema   |                         Description
----------+---------+------------+--------------------------------------------------------------
 pg_strom | 1.0     | public     | pg_strom -- yet another executor powered by stream processor
 plpgsql  | 1.0     | pg_catalog | PL/pgSQL procedural language
```

**Comment by kaigai** [comment]
Ah, did you see the wikipage on postgresql.org?

Sorry, it was written 3 years before, thus the description does not deflect the recent development status.
Because of data management burden, we gave up to use foreign-table for the purpose.
Instead of the previous design, you can run query on regular tables (so, PG-Strom is re-designed
to understand row-format in GPU device.)

**Comment by jordanrinke** [comment]
Fantastic. I will update the wiki here (in english) with the install process, and query sampls etc then - for anyone else that ends up here. I appreciate the help and the wonderful project.
