### ISSUE TITLE
ERROR:  PG-Strom: No OpenCL device available

### ISSUE THREAD

**Issue by IT302** [pg-strom/devel#132]
I get the following error when I run pg_ctl start:

LOG:  starting background worker process "PG-Strom OpenCL Server"
LOG:  database system was shut down at 2015-03-11 11:10:10 GMT
LOG:  PG-Strom: [0] OpenCL Platform: Intel(R) OpenCL
ERROR:  PG-Strom: No OpenCL device available. Please check "pg_strom.opencl_platform" parameter
LOG:  worker process: PG-Strom OpenCL Server (PID 13503) exited with exit code 1
LOG:  unregistering background worker "PG-Strom OpenCL Server"
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

How do I check or modify pg_strom.opencl_platform parameter.

Thanks

**Comment by kaigai** [comment]
Sorry for this misleadable error message.
It seems to me you run PG-Strom without GPU devices.
```
pg_strom.opencl_device_types = cpu
```
is an option, however, it is just for debug purpose option.
In our observation, GPU emulation mode by CPU is much less performance than native GPU.
I'd like to recommend to install nvidia's GPU and its driver.

**Comment by IT302** [comment]
pg_strom.opencl_device_types = cpu solved the problem. Thank you for your help.
