### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by hiteshramani** [pg-strom/devel#135]
Hi, I was trying to compile the code but was interrupted by the following output:

src/main.c:27:29: fatal error: utils/ruleutils.h: No such file or directory

As you mentioned in the other closed issue to download the custom_join branch, I did that and compiled it again, but the same issue prevailed. I tried locating the file ruleutils.h and couldn't find it after doing a make of custom_join branch too. Any solutions?

**Comment by kaigai** [comment]
Please use the "custom_join" branch of the following tree:
  https://github.com/kaigai/sepgsql/tree/custom_join
