### ISSUE TITLE
(JP) overflow付近のreal型データをグループ化した上で、統計情報集約関数を使ってGpuPreAggすると、結果不正

### ISSUE THREAD

**Issue by onlyindreams** [pg-strom/devel#171]

**Comment by onlyindreams** [comment]
掲題の件で統計情報集約関数を使用してGpuPreAggすると結果不正が発生しました。
参考: http://www.postgresql.org/docs/9.5/static/functions-aggregate.html#FUNCTIONS-AGGREGATE-STATISTICS-TABLE

再現クエリ(2パターン提示します)
```
set pg_strom.debug_force_gpupreagg to on;
drop table if exists orz; create table orz as select generate_series(1,10)::integer as key,1e+38::real as c1 from generate_series(1,1000);

--pattern-1
prepare p1 as select key, stddev(c1)  from orz  group by key; -- group by
explain verbose execute p1;
execute p1;
execute p1;
execute p1;
execute p1;
deallocate p1;

--pattern-2
prepare p2 as select key, corr(c1,c1)  from orz  group by key; -- group by
explain verbose execute p2;
execute p2;
execute p2;
execute p2;
execute p2;
deallocate p2;
```

実行結果(パターン1)
```
contrib_regression=# --pattern-1
contrib_regression=# prepare p1 as select key, stddev(c1)  from orz  group by key; -- group by
PREPARE
contrib_regression=# explain verbose execute p1;
                                                                     QUERY PLAN                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=197.55..200.05 rows=200 width=8)
   Output: key, pgstrom.stddev((pgstrom.nrows((c1 IS NOT NULL))), (pgstrom.psum((c1)::double precision)), (pgstrom.psum_x2((c1)::double precision)))
   Group Key: orz.key
   ->  Custom Scan (GpuPreAgg)  (cost=1000.00..1150.23 rows=200 width=24)
         Output: key, pgstrom.nrows((c1 IS NOT NULL)), pgstrom.psum((c1)::double precision), pgstrom.psum_x2((c1)::double precision)
         Bulkload: On (density: 100.00%)
         Reduction: Local + Global
         Features: format: tuple-slot, bulkload: unsupported
         ->  Custom Scan (BulkScan) on public.orz  (cost=0.00..146.70 rows=10170 width=8)
               Output: key, c1
               Features: format: heap-tuple, bulkload: supported
(11 rows)

contrib_regression=# execute p1;
 key |        stddev        
-----+----------------------
   8 |                    0
   4 | 1.29872373892486e+30
   1 | 1.83667272536343e+30
   5 |                    0
   3 | 1.29872373892486e+30
  10 | 1.29872373892486e+30
   9 |                    0
   6 | 1.29872373892486e+30
   2 | 1.83667272536343e+30
   7 |                    0
(10 rows)

contrib_regression=# execute p1;
 key |        stddev        
-----+----------------------
   8 | 1.29872373892486e+30
   4 |                    0
   1 | 1.29872373892486e+30
   5 |                    0
   3 |                    0
  10 | 1.83667272536343e+30
   9 | 1.29872373892486e+30
   6 | 1.29872373892486e+30
   2 | 1.29872373892486e+30
   7 |                    0
(10 rows)

contrib_regression=# execute p1;
 key |        stddev        
-----+----------------------
   8 |                    0
   4 |                    0
   1 |                    0
   5 | 1.29872373892486e+30
   3 |                    0
  10 |                    0
   9 | 1.29872373892486e+30
   6 | 1.29872373892486e+30
   2 |                    0
   7 |                    0
(10 rows)

contrib_regression=# execute p1;
 key |        stddev        
-----+----------------------
   8 | 1.83667272536343e+30
   4 |                    0
   1 | 1.83667272536343e+30
   5 | 1.29872373892486e+30
   3 |                    0
  10 | 1.29872373892486e+30
   9 | 1.29872373892486e+30
   6 | 1.29872373892486e+30
   2 | 1.29872373892486e+30
   7 | 1.83667272536343e+30
(10 rows)
```

実行結果(パターン2)
```
contrib_regression=# --pattern-2
contrib_regression=# prepare p2 as select key, corr(c1,c1)  from orz  group by key; -- group by
PREPARE
contrib_regression=# explain verbose execute p2;
                                                                                                                                                                                                                                             QUERY PLAN                                                                                                                                                                                                                                              
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=248.40..250.90 rows=200 width=8)
   Output: key, pgstrom.corr((pgstrom.nrows(((c1)::double precision IS NOT NULL), ((c1)::double precision IS NOT NULL))), (pgstrom.pcov_x(true, (c1)::double precision, (c1)::double precision)), (pgstrom.pcov_x2(true, (c1)::double precision, (c1)::double precision)), (pgstrom.pcov_y(true, (c1)::double precision, (c1)::double precision)), (pgstrom.pcov_y2(true, (c1)::double precision, (c1)::double precision)), (pgstrom.pcov_xy(true, (c1)::double precision, (c1)::double precision)))
   Group Key: orz.key
   ->  Custom Scan (GpuPreAgg)  (cost=1000.00..1153.53 rows=200 width=48)
         Output: key, pgstrom.nrows(((c1)::double precision IS NOT NULL), ((c1)::double precision IS NOT NULL)), pgstrom.pcov_x(true, (c1)::double precision, (c1)::double precision), pgstrom.pcov_x2(true, (c1)::double precision, (c1)::double precision), pgstrom.pcov_y(true, (c1)::double precision, (c1)::double precision), pgstrom.pcov_y2(true, (c1)::double precision, (c1)::double precision), pgstrom.pcov_xy(true, (c1)::double precision, (c1)::double precision)
         Bulkload: On (density: 100.00%)
         Reduction: Local + Global
         Features: format: tuple-slot, bulkload: unsupported
         ->  Custom Scan (BulkScan) on public.orz  (cost=0.00..146.70 rows=10170 width=8)
               Output: key, c1
               Features: format: heap-tuple, bulkload: supported
(11 rows)

contrib_regression=# execute p2;
 key |       corr        
-----+-------------------
   8 |                 2
   4 |                 2
   1 | 0.707106781186547
   5 |                 0
   3 |                 2
  10 |  1.41421356237309
   9 |  1.41421356237309
   6 |                 2
   2 |                 1
   7 |                 2
(10 rows)

contrib_regression=# execute p2;
 key | corr 
-----+------
   8 |    1
   4 |    1
   1 |     
   5 |     
   3 |    1
  10 |     
   9 |     
   6 |    1
   2 |     
   7 |     
(10 rows)

contrib_regression=# execute p2;
 key | corr 
-----+------
   8 |     
   4 |     
   1 |     
   5 |     
   3 |     
  10 |     
   9 |     
   6 |     
   2 |     
   7 |     
(10 rows)

contrib_regression=# execute p2;
 key |       corr        
-----+-------------------
   8 |                 1
   4 |                  
   1 |                  
   5 |                  
   3 |                  
  10 |                  
   9 |                  
   6 | 0.707106781186547
   2 |                 1
   7 |                  
(10 rows)
```

**Comment by kaigai** [comment]
同じパターンで、GPU側でオーバーフローを引き起こさないような計算式だと、結果は概ね正しい？
（浮動小数点計算の誤差程度と思える？）

gpupreagg_next_tuple_fallback() がコールされたかどうか、elog(INFO, ...) でも挟んで確認して
もらえるかな？

**Comment by onlyindreams** [comment]
fallbackはコールされていないようですね... gpupreaggg_next_tuple入った直後にelogをはさみました。

```
[nanzai@saba test]$ psql -af 171.sql
set pg_strom.debug_force_gpupreagg to on;
SET
drop table if exists orz; create table orz as select generate_series(1,10)::integer as key,1e+38::real as c1 from generate_series(1,1000);
DROP TABLE
SELECT 10000
--pattern-1
prepare p1 as select key, stddev(c1)  from orz  group by key; -- group by
PREPARE
explain verbose execute p1;
                                                                     QUERY PLAN                                                                      
-----------------------------------------------------------------------------------------------------------------------------------------------------
 HashAggregate  (cost=197.55..200.05 rows=200 width=8)
   Output: key, pgstrom.stddev((pgstrom.nrows((c1 IS NOT NULL))), (pgstrom.psum((c1)::double precision)), (pgstrom.psum_x2((c1)::double precision)))
   Group Key: orz.key
   ->  Custom Scan (GpuPreAgg)  (cost=1000.00..1150.23 rows=200 width=24)
         Output: key, pgstrom.nrows((c1 IS NOT NULL)), pgstrom.psum((c1)::double precision), pgstrom.psum_x2((c1)::double precision)
         Bulkload: On (density: 100.00%)
         Reduction: Local + Global
         Features: format: tuple-slot, bulkload: unsupported
         ->  Custom Scan (BulkScan) on public.orz  (cost=0.00..146.70 rows=10170 width=8)
               Output: key, c1
               Features: format: heap-tuple, bulkload: supported
(11 rows)

execute p1;
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
psql:171.sql:7: INFO:  gpupreagg_next_tuple have called. gpupreagg->needs_fallback=0
 key |        stddev        
-----+----------------------
   8 | 1.29872373892486e+30
   4 | 1.29872373892486e+30
   1 |                    0
   5 | 1.29872373892486e+30
   3 |                    0
  10 | 1.29872373892486e+30
   9 | 1.29872373892486e+30
   6 | 1.83667272536343e+30
   2 | 1.29872373892486e+30
   7 | 1.83667272536343e+30
(10 rows)
```

データを減らしていくと、不正な返却値の大きさも減少していくように見えています。
```
nanzai=# select key,stddev(20000000000::real) from (select generate_series(1,10) as key from generate_series(1,1000)) as t group by key;
 key |      stddev      
-----+------------------
   8 | 262.275170385992
   4 |                0
   1 |                0
   5 |                0
   3 |                0
  10 | 262.275170385992
   9 | 262.275170385992
   6 |                0
   2 |                0
   7 | 262.275170385992
(10 rows)

nanzai=# select key,stddev(9000000000::real) from (select generate_series(1,10) as key from generate_series(1,1000)) as t group by key;
 key |      stddev      
-----+------------------
   8 |                0
   4 | 131.137585192996
   1 |                0
   5 | 131.137585192996
   3 |                0
  10 |                0
   9 |                0
   6 | 131.137585192996
   2 | 131.137585192996
   7 | 131.137585192996
(10 rows)

nanzai=# select key,stddev(6000000000::real) from (select generate_series(1,10) as key from generate_series(1,1000)) as t group by key;
 key |      stddev      
-----+------------------
   8 | 65.5687925964979
   4 | 65.5687925964979
   1 | 65.5687925964979
   5 |                0
   3 |  92.728275758396
  10 |  92.728275758396
   9 |  92.728275758396
   6 |  92.728275758396
   2 |  92.728275758396
   7 | 65.5687925964979
(10 rows)

nanzai=# select key,stddev(5000000000::real) from (select generate_series(1,10) as key from generate_series(1,1000)) as t group by key;
 key |      stddev      
-----+------------------
   8 | 65.5687925964979
   4 | 65.5687925964979
   1 | 65.5687925964979
   5 | 65.5687925964979
   3 |                0
  10 |                0
   9 | 65.5687925964979
   6 | 65.5687925964979
   2 |                0
   7 | 65.5687925964979
(10 rows)
```

**Comment by kaigai** [comment]
これは仕様のような気がしています。

Real型最大値をFloat型にキャストして計算しているので、計算順序によっては浮動小数点計算誤差が発生し、それが最終結果に波及しているように見えます。
特に stddev() や corr() は内部計算で自乗を計算するので、浮動小数点計算誤差が発生しやすい。
（実際に printfを挟むと仮数部の最下位に±1ていどの差がありました）

PostgreSQLでは無限大への発散はチェックしていましたが、桁落ちはチェックしていません。
これ、直すべき問題なのかどうか、少し考えます。

**Comment by ahase** [comment]
指摘内容の意図は理解できますが、この件に関しては上記の結果で正しいと判断します。

詳細は別途記載する予定ですが、一般的にコンピュータの浮動小数型は内部を2進数の指数表示でデータを持っており、10新数の値を正確に表現する事が出来ません。また有効桁数も限られているため、演算仮定置いて丸め誤差が発生します。このため、計算過程において一定の誤差が発生する事を前提に使用する必要があります。

浮動小数点の話は以下のURLに詳しい説明がありますので、そちらを参考にしてください。
http://www.cc.kyoto-su.ac.jp/~yamada/programming/float.html

素のpostgreSQLの結果がとPG-Stromの結果が異なることを理由に、PG-Stromが間違っているとの報告になっていますが、PostgreSQLの自体、同様の問題を含んでおり、今回のテストケースではたまたま正しい結果が得られたにすぎません。

stddevの演算は、以下の式で計算できます。

　stddev = sqrt((sum(x^2) - count(x) * avg(x)^2) / (count(x) - 1));

PostgreSQLのreal型のstddevはfloat8_stddev_samp() に記載されており、以下の処理で実装しています。
ここで、stddev^2 < 0 の場合、例外処理として、結果を 0 とする処理が存在します。
(定義上stddev^2は正値になる。値が負の場合sqrt()の結果が虚数になる。等の問題があり、明らかな計算誤差を0に丸めるのは妥当な処理だと思います。)

<pre>
numerator = N * sumX2 - sumX * sumX;
CHECKFLOATVAL(numerator, isinf(sumX2) || isinf(sumX), true);

/* Watch out for roundoff error producing a negative numerator */
if (numerator <= 0.0)
  PG_RETURN_FLOAT8(0.0);

PG_RETURN_FLOAT8(sqrt(numerator / (N * (N - 1.0))));
</pre>

今回問題視された事例では、素のPosggreSQLの処理結果は、stddev^2 負の値になっているため、上記の例外処理により、0に補正されています。つまるところ、結果が、たまたま、テストコードの期待値に補正されて出力されたにすぎません。

<pre>
create table orz as select generate_series(1,10)::integer as key,1.1e+38::real as c1 from generate_series(1,1000);
select 
　key,
　stddev(c1),
　(sum(c1::real^2) - count(c1::real) * avg(c1::real)^2)/(count(c1) * (count(c1)-1)) 
from orz group by key;
 key | stddev |       ?column?
-----+--------+-----------------------
   8 |      0 | -9.22404957056932e+58
   4 |      0 | -9.22404957056932e+58
   1 |      0 | -9.22404957056932e+58
   5 |      0 | -9.22404957056932e+58
   3 |      0 | -9.22404957056932e+58
  10 |      0 | -9.22404957056932e+58
   9 |      0 | -9.22404957056932e+58
   6 |      0 | -9.22404957056932e+58
   2 |      0 | -9.22404957056932e+58
   7 |      0 | -9.22404957056932e+58
(10 rows)
</pre>

このため、入力値を 1.1e+38 に変更して同様のコードを実行すると、今回はプラス方向の誤差が発生し、例外処理が実行されないため、stddev()の結果は誤差を含んだ値が出力されます。

<pre>
create table orz as select generate_series(1,10)::integer as key,1.1e+38::real as c1 from generate_series(1,1000);
select 
　key,
　stddev(c1),
　(sum(c1::real^2) - count(c1::real) * avg(c1::real)^2)/(count(c1) * (count(c1)-1)) 
from orz group by key;
 key | stddev |       ?column?
-----+----------------------+----------------------
   8 | 1.50338141835761e+31 | 2.25659784137142e+59
   4 | 1.50338141835761e+31 | 2.25659784137142e+59
   1 | 1.50338141835761e+31 | 2.25659784137142e+59
   5 | 1.50338141835761e+31 | 2.25659784137142e+59
   3 | 1.50338141835761e+31 | 2.25659784137142e+59
  10 | 1.50338141835761e+31 | 2.25659784137142e+59
   9 | 1.50338141835761e+31 | 2.25659784137142e+59
   6 | 1.50338141835761e+31 | 2.25659784137142e+59
   2 | 1.50338141835761e+31 | 2.25659784137142e+59
   7 | 1.50338141835761e+31 | 2.25659784137142e+59
(10 rows)
</pre>

なので、統計関数における動作検証は、内部演算における計算誤差と、有効桁数を踏まえて議論する必要があります(テストの意図は理解できますが、入力データは少々現実的な内容に即していないと思います)。

**Comment by ahase** [comment]
計算結果に関する詳細です。
結果を検証してみましたが、入力値が大きすぎることが原因で、導出過程において有効桁数外の値(計算誤差)が導きされており、それが、そのまま結果になっています。
以下、上記誤差に対する詳細です。

まず、入力の 1e+38 に関してですが、上記値は単精度浮動小数点では正確に表す事が出来ません。
以下のコードを書いてテストしてみると、
<pre>
    float  a  = 1.0e+38;
    printf("in=1.0e+38\n"
           "value       = %lf\n"
           "bit pattern = %08x\n"
           "\n",
           a, *(unsigned int *)&a);
</pre>
内部では、以下のようになっており、値は1e+38でない事が解ります(有効数字8桁目に誤差が発生しています)。但し、全データに対して同様の誤差が発生するため、標準偏差(stddev)の結果は 0 になるべきという点は同じです。
<pre>
in=1.0e+38
value       = 99999996802856924650656260769173209088.000000
bit pattern = 7e967699
</pre>

PostgreSQLは統計関数の内部演算は倍精度浮動小数点(float型)で行うため、x::float, (x::float)^2 に対して同様の確認を行うと、以下のようになります。
<pre>
(in=1.0e+38)::float
value       = 99999996802856924650656260769173209088.000000
bit pattern = 47d2ced320000000

((in=1.0e+38)::float)^2
value       = 999999936057139515185509640809410029252845031732337825041960733873216 5791744.000000
bit pattern = 4fb61bcc8f59dc40
</pre>
doubleの有効桁数は14桁ですので、入力時の有効桁数を無視すると、以下のようになります。
(今回は、全ての入力値が同値である事が解っており、stddevが0にならない事の確認のために内部演算の有効桁数を検証していますが、実際は入力データ有効桁数で扱います)
<pre>
x   = 9.9999996802857e+37 
x^2 = 9.9999993605714e+75
</pre>

PostgreSQLの内部処理では、x, x^2に対して、for loop で、sum(x::float), sum((x::float)^2)を求めています。
sum() を x*1000 と掛算で求めた場合と、for loop で1000回加算した場合では結果は以下のようになります。

<pre>
[sumを掛け算で求めた場合]
sum((in=1.0e+38)::float)
value       = 99999996802856924650656260769173209088000.000000
　　　　　　= 9.9999996802857e+40 (有効数字14桁)
bit pattern = 48725dfa2d400000

sum(((in=1.0e+38)::float)^2)
value       = 9999999360571394329102817747491079215043859038648125759051674521942234117439488.000000
            = 9.9999993605714e+78 (有効数字14桁)
bit pattern = 50559725c3fdc116

[sumをfor loopで求めた場合(1000回加算)]
sum((in=1.0e+38)::float)
value       = 99999996802856924650656260769173209088000.000000
            = 9.9999996802857e+40 (有効数字14桁)
bit pattern = 48725dfa2d400000

sum(((in=1.0e+38)::float)^2)
value       = 9999999360571302180847607759952718536769635827019846725843199041469886595334144.000000
            = 9.9999993605713e+78 (有効数字14桁)
bit pattern = 50559725c3fdc0de
</pre>

sum(x)では掛算でもfor loopでも値は一緒ですが、sum(x^2)は有効数字15桁目の四捨五入により、有効数字14桁目が異なっています。
これは、real型からfloat型へのキャスト(仮数部23bit→52bitへの変換)に伴い、x::floatは下位19bitが空きとなっているためです。
for loopで1000回の加算を正確に行うためには、999回目の値を正確に計算/保持できる必要があります。
2^10 = 1024なので、桁上がりを考慮しても、仮数部に10bitの空きがあれば正しく計算できますので、cast時の仮数部の空きが精度を保証している事になります。
これに対して、sum(x^2)では、(x::float)^2 を計算した時点で、仮数部に4bitしか空きがないため、for loopで加算処理を行うことにより精度落ちが発生します。


次に、上記のsum(x), sum(x^2) から、stddev を導出するまでの計算仮定で値がどうなるかを確認してみます。
但し、値が負だとsqrtがエラーになるので、計算式にfabs()を入れておきます。
valueは掛算で求めたsum()による値で計算した結果で、value(for)はfor loopで求めた結果です。
<pre>
[N * sum(x^2)]
value       = 9999999360571393512932557316172882306179144490202275287614685167686621896529412096.000000
            = 9.9999993605714e+81 (有効数字14桁)
value(for)  = 9999999360571302523112555682763575305003225798948751762252259093254498171844820992.000000
　　　　　　= 9.9999993605713e+81 (有効数字14桁)

[sum(x)^2]
value       = 9999999360571395197929224013087869472867587428929192389936211576472401965505052672.000000
            = 9.9999993605714e+81 (有効数字14桁)
value(for)  = 9999999360571395197929224013087869472867587428929192389936211576472401965505052672.000000
            = 9.9999993605714e+81 (有効数字14桁)

[N * sum(x^2) - sum(x)^2]
value       = -1684996666696914987166688442938726917102321526408785780068975640576.000000
            = -1.6849966666969e+66 (有効数字14桁)
value(for)  = -92674816668330324294167864361629980440627683952483217903793660231680.000000
            = -9.2674816668330e+67 (有効数字14桁)

[N * sum(x^2) - sum(x)^2 / (count(X) - (count(x) - 1)]
value       = -1686683350046961840287810509264203140508955044607550812061696.000000
            = -1.6866833500470e+60 (有効数字14桁)
value(for)  = -92767584252582902286265347539001083521707004540536646950453248.000000
            = -9.2767584252583e+61 (有効数字14桁)

[sqrt(fabs(N * sum(x^2) - sum(x)^2 / (count(X) - (count(x) - 1)))]
value       = 1298723738924857552231498514432.000000
            = 1.2987237389249e+30 (有効数字14桁)
value(for)  = 9631593027769752299778544238592.000000
            = 9.6315930277698e+30 (有効数字14桁)
</pre>

計算結果を見ると、「N*sum(x^2)」は有効数字13桁で一致しています(sum(x^2)の誤差がそのまま出ているだけです)。
「sum(x)^2」は値が一致しています。
「N * sum(x^2) - sum(x)^2」で大きく違いが出ているようですが、計算元の値が「9.9999993605714e+81」なので、
「-9.2674816668330e+67 (-0.000000000000092674816668330e+81)」は入力値の有効桁数外の値となるため、これ以降の演算で求まる値は、浮動小数点誤差でしかありません。
(count(x) / (count(x)-1)は、整数値による割り算で、sqrt()は、同精度の浮動小数点の割り算に等しいため、有効数字は変わりません。
つまるところ、今回の問題は、入力値が10e+38と非常に大きい値であるため、導出過程で発生して計算誤差が結果として出力されたという状況にすぎません。

PostgreSQLとpg-stromでは計算順序が異なるため、丸め誤差により、計算結果が異なります。
PostgreSQLでは、以下の様に１個づつ加算する。
　((((1e38^2 + 1e38^2) + 1e38^2) + 1e38^2) + 1e38^2) ... 
PG-Stromでは並列で計算するため、計算順序が異なります。
　((1e38^2 + 1e38^2) + (1e38^2 + 1e38^2)) + ((1e38^2 + 1e38^2) + (1e38^2 + 1e38^2)) ...
浮動小数点演算では、浮動賞終点誤差の影響により、数学の可換則が成り立ちません。
  (a+b)+c = a+(b+c)
これによる計算誤差が、PostgreSQLとの結果不一致という結果を引き起こしていますが、
そもそもが、有効数字外の値ですので、今回のケースでは、計算誤差として取り扱うべき値です。

今回の例では、for loopによるsum(x^2) の計算誤差は、有効数字13桁まで正確な値が得られていますが、sum(x^2) の計算では、x^2の時点で、下位4bitしか空きがなく、1000回の加算を正しく行うためには、10bitの仮数部が必要なため、仮数部が6bit不足しています。2^6=64ですので、最悪、ここで、有効数字の下位3桁分の誤差が発生する可能性があります。

**Comment by kaigai** [comment]
本件に関しては、以下のように結論付ける事にします。

GPU並列処理に伴う計算順序の入れ替えは防ぎようがない。
したがって、CPUと異なる計算順序に伴う、有効桁数を越えた誤差の発生はPG-Stromではケアしない。
利用者が自らの責任で有効桁数を意識した使い方をする必要がある。

このような非互換が発生する可能性がある事は、FAQ文書に記載するものとする。

**Comment by onlyindreams** [comment]
```
select key,stddev(5000000000::float) from (select generate_series(1,10) as key from generate_series(1,1000)) as t group by key;
```

上記SQLを実行した場合のstddevの最終関数であるfloat8_stddev_samp実行前の結果は以下となりました。

```
<PostgreSQL>
N=1000.000000
sumX=5000000000000.000000
sumX2=24999999999999763021824.000000

<pg_strom>
N=1000.000000
sumX=5000000000000.000000
sumX2=25000000000000006291456.000000
```

PostgreSQLでのsumX2の計算ループは、終盤では状態値と入力値の差が大きいため、入力値が持っていた有効桁数内の情報が情報落ちによって失われてしまう。
だからPostgreSQLのsumX2は値が理論値よりも小さくなっている、pg_strom側も有効数字外の計算によってプラス方向に誤差が出てしまう。
結果としてPostgreSQLとpg_stromのsumX2(値の2乗の和)に誤差が生じることから、float8_stddev_sampによる計算後もそれぞれで異なる結果が導出される。

テストケースにおける対処としましては、今回のような浮動小数点誤差が発生する可能性のあるテストケースは排除することに致します。
