### ISSUE TITLE
Unable to build (utils/ruleutils.h: No such file or directory)

### ISSUE THREAD

**Issue by titouanc** [pg-strom/devel#172]
#135 suggests to checkout the `custom_join` branch of https://github.com/kaigai/sepgsql, but this branch doesn't exist (anymore ?).

I'm trying to build pgstrom for Postgres 9.4 on branch `opencl` (I'm using Beignet for Intel integrated GPU), but `master` seems to have the same problem.

**Comment by kaigai** [comment]
Now all the custom_join features got merged to the upstream version of PostgreSQL with some modifications.
Please use PostgreSQL 9.5alpha instead, with master branch of PG-Strom.

**Comment by kaigai** [comment]
Close the topic because of no updates during 2 weeks.

**Comment by titouanc** [comment]
Sorry, was AFK most of the time these days.

Unfortunately, building from master is not an option, since I have no NVidia card or the CUDA SDK. What are the plans to support OpenCL at the moment ?
