### ISSUE TITLE
(JP) hash aggregate で無限ループに落ちる可能性がある

### ISSUE THREAD

**Issue by ahase** [pg-strom/devel#205]
hash aggregateのコードで、hash_slot の確保は、以下のようなループで、空slotを探す。
この時に集約できないデータが多く、hash tableがフルに埋まってしまった場合、処理が無限ループに落ちる。
<pre>
retry:
  cur_slot.value = atomicCAS(...);
  ...
  else {
     index = (index + 1) % hash_size;    // 確保できなかったら index を + 1 して、次を探す
     goto retry;
  }
</pre>

問題は集約後のデータ数とhash tableサイズで決まるので、local_reduction, global_reduction, final_reductionのすべてで発生する可能性がある。

対策としては以下ように修正するしかないので、方針を決めてもらえないでしょうか？

- hash table を必ずデータ数より大きくする
- n回 retry したらエラーにする
- hash table を1周回ったらエラーにする

**Comment by kaigai** [comment]
final_reductionの特性からhash tableを必ずデータ数より多くする事はできません。

hash_slotの占有率が高くなると早晩性能劣化が酷い事になります。
なので、一週回るのを待たず、ある程度早い段階でCPUにエラーを返したいです。
判断基準として、hash_slot の使用率が 75% を越えたら「もうダメ！」と判断させ
ましょうか。まだずいぶん残りはがありますが、90%とかだと平均して10step回ら
ないと空きスロットを見つけられないという事ですからね。

現状、Global/Final Reductionに使う Hash Slot は pagg_hashslot 構造体の
フラット配列になっています。

新たに以下のような kern_global_hashslot という型を定義して、誰かがHashSlotを占有する
たびに hash_usage を atomicAdd するのではどうでしょう？
```
typedef struct
{
    cl_uint    hash_usage;    /* number of occupied hash slot */
    cl_uint    hash_length;        /* length of hash slot */
    pagg_hashslot   hash_slot[FLEXIBLE_ARRAY_MEMBER];
} kern_global_hashslot;
```

これで、Global Hashslot の占有率を計算できるハズです。

**Comment by kaigai** [comment]
```check_global_hashslot_usage``` でスロットの空きを見ているので、今はもう再現しないはず。
