### ISSUE TITLE
(JP) GPUのkernelでセットしたエラーコードをCPU側で参照していない(preagg)

### ISSUE THREAD

**Issue by ahase** [pg-strom/devel#206]
preagg branch だけの問題だと思いますが、GPUのkernelでセットしたエラーコードをCPU側の処理で見ていない。このため、集約関数がoverflow 等でCpuRecheckのエラーを設定しているにもかかわらず、それを無視して後処理を実行し、間違った結果を出力する。

**Comment by kaigai** [comment]
本来は、これらの値を見てCPU fallbackまたはバッファ拡張を試みねばならないのですが、
実装が追いついていません。

**Comment by kaigai** [comment]
修正したんだが、どこのコミットだったか…。
