### ISSUE TITLE
Issues making pg-strom

### ISSUE THREAD

**Issue by sjanahan** [pg-strom/devel#207]
Hi,

I am attempting to build pg-strom for use with a test postgres 9.6 server instance and I am getting the following error on make:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fpic -Wall -DPGSTROM_DEBUG=1 -O2 -DCMD_GPUINFO_PATH=\"/media/2TB/pgsql_95/bin/gpuinfo\" -I /usr/local/cuda/include -I. -I./ -I/media/2TB/pgsql_95/include/server -I/media/2TB/pgsql_95/include/internal -D_GNU_SOURCE   -c -o src/main.o src/main.c
In file included from src/main.c:34:0:
src/pg_strom.h:66:2: error: #error PG-Strom expects inline function is supported by compiler
 #error PG-Strom expects inline function is supported by compiler
  ^
make: *** [src/main.o] Error 1

I am using Ubuntu 12.04 and my gcc version is as follows:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.1-2ubuntu1~12.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.1 (Ubuntu 4.8.1-2ubuntu1~12.04) 

gcc 4.8 is the newest version available for my version of Ubuntu and am pretty sure it will support inline functions.

The error is that PG_USE_INLINE is not defined in the pg_strom.h line 65. Is there any way to turn that on? What am I missing here?

Regards,
Janahan

**Comment by sjanahan** [comment]
I added a #def PG_USE_INLINE and was able to make pg-strom. 

Please advise if that isn't desirable.

**Comment by kaigai** [comment]
It didn't follow the prerequisite change in the upcoming v9.6.
Hackers decided that compiler must have "inline" function capability, so previous PG_USE_INLINE check has gone. Of course, your gcc has this capability.

It was fixed at b6d316f5f0352a06df290b629486fc3b00f9969c

Thanks,

**Comment by kaigai** [comment]
already solved.
