### ISSUE TITLE
OpenCL branch status

### ISSUE THREAD

**Issue by stalkerg** [pg-strom/devel#210]
Hello.
What is the current status OpenCL? And plans for him?

Thanks.

**Comment by kaigai** [comment]
I decided to move CUDA entirely, because of software quality of OpenCL driver and difficulty of code optimization.
Even though 'opencl' branch is still in the repository, it is deprecated and not maintained.

**Comment by stalkerg** [comment]
Thanks for answer. 
I interesting because Intel Beignet and Mesa Clover (for AMD) have a good progress in terms of quality.

PS I was can't build branch for 9.5/9.6 postgres. :(

**Comment by akorotkov** [comment]
Hello, Kaigai!

Did you consider software quality of OpenCL only for NVidia GPU or also Intel Beignet and Mesa Clover (for AMD) as Stalkerg mentioned? Are you interested if we contribute in OpenCL branch?

**Comment by kaigai** [comment]
> PS I was can't build branch for 9.5/9.6 postgres. :(

Hmm... It was designed to the previous custom-scan interface; that is not compatible with the latest version in v9.5/v9.6.

**Comment by kaigai** [comment]
> Did you consider software quality of OpenCL only for NVidia GPU or also Intel Beignet and Mesa Clover (for AMD) as Stalkerg mentioned? Are you interested if we contribute in OpenCL branch?

We tried both of Intel, NVIDIA and AMD. The most problematic driver was Intel's one.
I could see some unbelievable bugs. In addition, some minor behavior differences made
troubles, thus we had to put workaround to avoid troubles.

I'm appreciate your offer for contribution, however, our team does not have enough
capability to maintain two (entirely) different code bases.
In short term, we like to focus on CUDA based implementation.

Thanks,

**Comment by stalkerg** [comment]
> I'm appreciate your offer for contribution, however, our team does not have enough
capability to maintain two (entirely) different code bases.

Do I understand you: you do not take the patches associated with OpenCL, and we'd better make fork?

Thanks.

**Comment by kaigai** [comment]
> Do I understand you: you do not take the patches associated with OpenCL, and we'd better make fork?

Yes. Our (small) team wants to focus on CUDA now. Not capable to support OpenCL also.

Thanks,

**Comment by akorotkov** [comment]
Ok. So, if we're interested in OpenCL branch then we have to create our fork and maintain it ourselves. We would be interested in it. However, I'm in doubt about license. The license our PGStrom is GNU GPL v2. If we will create and maintain our fork, we would like to have it under PostgreSQL license.

**Comment by kaigai** [comment]
>  The license our PGStrom is GNU GPL v2.

Sorry, it's our project strategy. We'd like to ensure the branch version can also give us feedback for further improvement. I hope you understand.

**Comment by stalkerg** [comment]
"give us feedback" but OpenCL feedback not intersted... ok.

**Comment by kaigai** [comment]
Sorry, our team is not capable to maintain two different code bases now.
Even if new enhancement is done with OpenCL, we can learn better algorithm to utilize GPU.

**Comment by ggschaefer** [comment]
Not sure that the CUDA approach and locking into NVIDIA is one I like.  Open development to me means that you are not targeting only 1 vendors solution and the whole premise behind OpenCL.  

AMD knows that CUDA has many developers and even built a tool to convert the code.  You really need to reconsider as I love the product you are building with the exception that you are building it to support only 1 platform (monopoly).

AMD is trying to help.  See below:

HIP-ifying CUDA Application to Run on AMD GPUs

To bring applications written for CUDA onto AMD platforms, AMD announces the new HIP tool. AMD testing shows that in many cases 90 percent or more of CUDA code can be automatically converted into C++ by HIP with the final 10 percent converted manually in the widely popular C++ language. This greatly expands the installed hardware base available to run what were formerly exclusively CUDA-based applications. At SC15, AMD is demonstrating the potential for HIP, running the CUDA-generated Rodinia benchmark suite on AMD GPUs.

**Comment by kaigai** [comment]
At this moment, I don't plan to back to OpenCL, or something other than CUDA.

I know AMD takes new strategy, like OpenGPU, to involve open source community.
However, database software is an infrastructure for other application also, we have
to determine the infrastructure of infrastructure carefully.
Right now, CUDA already has widespread user base and stable code base.
No need to become an early adopter of OpenCL, OpenGPU, .... and so on.

**Comment by stalkerg** [comment]
> Right now, CUDA already has widespread user base and stable code base.

But normal work only on nVidia Hardware. AMD and Intel users cry. :(
