### ISSUE TITLE
(JP) gpupreagg のエラー

### ISSUE THREAD

**Issue by ahase** [pg-strom/devel#213]
master branch の 以下の commit id のコードでエラーが発生する。 
<pre>
commit 257aab062070b6880c9c8c319c87ee6898807331
Author: KaiGai Kohei <kaigai@kaigai.gr.jp>
Date:   Fri Nov 13 13:51:57 2015 +0900

    TextOutCustomScan get ripped out
</pre>

実行は、以下のスクリプトを使用
<pre>
#!/bin/sh

#N=200000
N=$1
PORT=4321

ENABLE_PGSTROM="set enable_seqscan=off; set pg_strom.enabled=on; set pg_strom.debug_force_gpuscan=on; set pg_strom.debug_force_gpupreagg=on"
DISABLE_PGSTROM="set enable_seqscan=on; set pg_strom.enabled=off; set pg_strom.debug_force_gpuscan=off; set pg_strom.debug_force_gpupreagg=off"

psql -p ${PORT} postgres -c "drop table tbl;"

psql -p ${PORT} postgres -c "
${DISABLE_PGSTROM}; 
create table tbl (id int primary key, x integer, y integer); insert into tbl (select id, random() * 100, random() * 100 FROM generate_series(1,${N}) id);
"
echo "Sort"
echo "Scan by CPU"
psql -p ${PORT} postgres -c "${DISABLE_PGSTROM}; select * from tbl where x < 10;" | sort > cpu.out
echo "Scan by GPU"
psql -p ${PORT} postgres -c "${ENABLE_PGSTROM}; select * from tbl where x < 10;" | sort > gpu.out
echo "Check result"
diff cpu.out gpu.out

echo "Group reduction"
echo "Reduction by CPU"
psql -p ${PORT} postgres -c "${DISABLE_PGSTROM}; select sum(y) from tbl group by x;" | sort > cpu.out
echo "Reduction by GPU"
psql -p ${PORT} postgres -c "${ENABLE_PGSTROM}; select sum(y) from tbl group by x;" | sort > gpu.out
echo "Check result"
diff cpu.out gpu.out

echo "Nogroup reduction"
echo "Reduction by CPU"
psql -p ${PORT} postgres -c "${DISABLE_PGSTROM}; select sum(x) from tbl;" | sort > cpu.out
echo "Reduction by GPU"
psql -p ${PORT} postgres -c "${ENABLE_PGSTROM}; select sum(x) from tbl;" | sort > gpu.out
echo "Check result"
diff cpu.out gpu.out
</pre>

以下のように、データ数=10 で実行した場合、集約関数のGPU側の処理でエラーとなる。
<pre>
[a-hasega@saba test]$ sh ./test_scan.sh 10
DROP TABLE
INSERT 0 10
Sort
Scan by CPU
Scan by GPU
Check result
Group reduction
Reduction by CPU
Reduction by GPU
WARNING:  failed on cuCtxSynchronize: CUDA_ERROR_ASSERT - device-side assert triggered
WARNING:  AbortTransaction while in ABORT state
ERROR:  failed on cuCtxGetLimit: CUDA_ERROR_ASSERT - device-side assert triggered
ERROR:  failed on cuMemFree: CUDA_ERROR_ASSERT - device-side assert triggered
Check result
1,14d0
<
< -----
< (10 rows)
<   18
<    2
<   36
<   41
<   45
<   49
<   64
<   73
<   81
<   91
<  sum
Nogroup reduction
Reduction by CPU
Reduction by GPU
Check result
</pre>

但し、データ数=100の場合は正しく動作する。
<pre>
[a-hasega@saba test]$ sh ./test_scan.sh 100
DROP TABLE
INSERT 0 100
Sort
Scan by CPU
Scan by GPU
Check result
Group reduction
Reduction by CPU
Reduction by GPU
Check result
Nogroup reduction
Reduction by CPU
Reduction by GPU
Check result
</pre>

**Comment by ahase** [comment]
原因は以下の要因でした。
・動作検証のため、強制的にgpupreaggに落としていた
・データ数10個に対して、hashslot=10, hashlimit=7 で、全データのキーがバラバラのためhash slotが不足
・gpupreagg_global_reduction() でhashslotが確保できない場合に、recheckに落とす処理がない
　このため、owner_index=0xffffffff で、reduction処理に入り、assert()で落ちた

**Comment by ahase** [comment]
既に、check_global_hashslot_usage()で、recheck error がセットされていたので、
データのコピー前にowner_indexのチェックを入れるだけだった。
但し、hashslot のサイズの見積もりは要検討。

<pre>
diff --git a/src/cuda_gpupreagg.h b/src/cuda_gpupreagg.h
index 793bc3b..bb44aab 100644
--- a/src/cuda_gpupreagg.h
+++ b/src/cuda_gpupreagg.h
@@ -965,28 +965,30 @@ gpupreagg_global_reduction(kern_gpupreagg *kgpreagg,
 	 * Once atomic operations got finished, values of pagg_datum in the
 	 * respobsible thread will have partially aggregated one.
 	 */
-	for (attnum = 0; attnum < nattrs; attnum++)
-	{
-		if (gpagg_atts[attnum] != GPUPREAGG_FIELD_IS_AGGFUNC)
-			continue;
-
-		/*
-		 * Reduction, using global atomic operation
-		 *
-		 * If thread is responsible to the grouping-key, other threads but
-		 * NOT responsible will accumlate their values here, then it shall
-		 * become aggregated result. So, we mark the "responsible" thread
-		 * identifier on the kern_row_map. Once kernel execution gets done,
-		 * this index points the location of aggregate value.
-		 */
-		if (get_global_id() < kds_dst->nitems &&
-			get_global_id() != owner_index)
+	if (owner_index != (cl_uint)(0xffffffff)) {
+		for (attnum = 0; attnum < nattrs; attnum++)
 		{
-			assert(owner_index < kds_dst->nrooms);
-			gpupreagg_global_calc(&kcxt,
-								  attnum,
-								  kds_dst, owner_index,
-								  kds_dst, get_global_id());
+			if (gpagg_atts[attnum] != GPUPREAGG_FIELD_IS_AGGFUNC)
+				continue;
+
+			/*
+			 * Reduction, using global atomic operation
+			 *
+			 * If thread is responsible to the grouping-key, other threads but
+			 * NOT responsible will accumlate their values here, then it shall
+			 * become aggregated result. So, we mark the "responsible" thread
+			 * identifier on the kern_row_map. Once kernel execution gets done,
+			 * this index points the location of aggregate value.
+			 */
+			if (get_global_id() < kds_dst->nitems &&
+				get_global_id() != owner_index)
+			{
+				assert(owner_index < kds_dst->nrooms);
+				gpupreagg_global_calc(&kcxt,
+									  attnum,
+									  kds_dst, owner_index,
+									  kds_dst, get_global_id());
+			}
 		}
 	}
 out:
</pre>

**Comment by kaigai** [comment]
c95e2ce252e48cea0fb45c68effb77acad2b9e1c
にて修正です。
