### ISSUE TITLE
Unable to start postgres 9.5 cluster after install of pg_strom due to missing CUDA object 

### ISSUE THREAD

**Issue by corbettht** [pg-strom/devel#217]
**Relevant Versions:**
Postgresql: 9.5.0
OS: Ubuntu 14.04.3 LTS (GNU/Linux 3.16.0-34-generic x86_64)
CUDA Compiler Version: V7.5.17
pg_strom commit: d132bf3ace9a2191aedad71c13aea23d0d181585 
CUDA GPU: Nvidia K40c

**Summary**
After compiling and installing pg_strom per the instructions in the wiki and adding
>  shared_preload_libraries = '$libdir/pg_strom'

to my /etc/postgresql/9.5/main/postgresql.conf file, my postgresql 9.5 cluster is unable to start and gives the following error:
>  $ pg_ctlcluster 9.5 main start
>The PostgreSQL server failed to start. Please check the log output:
2016-01-19 20:23:20 UTC [3860-1] FATAL:  could not load library "/usr/lib/postgresql/9.5/lib/pg_strom.so": libnvrtc.so.7.5: cannot open shared object file: No such file or directory

I am not sure if this is a pg_strom issue or an issue with my CUDA installation. Any guidance on how to proceed would be appreciated.

**Comment by kaigai** [comment]
A quick workaround is:

```
# echo /usr/local/cuda/lib64 > /etc/ld.so.conf.d/cuda-x86_64.conf
```

It indicates dynamic linker to find libraries under the CUDA installation.
Essentially, It shall be configured "-rpath" option on build, however,
it conflicts with configuration come from PostgreSQL, so not solved yet.

**Comment by corbettht** [comment]
Thanks for your quick reply -- that seems to be working. 

For anyone else who has this problem, I had to modify the bash command a little:
```
# sudo sh -c "echo /usr/local/cuda/lib64 > /etc/ld.so.conf.d/cuda-x86_64.conf"
# sudo ldconfig 
# bash 
```

**Comment by kaigai** [comment]
Solved.
