### ISSUE TITLE
pg_strom ignores child tables

### ISSUE THREAD

**Issue by GeroNiessen** [pg-strom/devel#228]
When using partitioning, pg_strom does not scan child tables when you run a query against the master table, which is not correct. If you switch off pg_strom, postgres does scan child tables when you run a query against the master table.

**Comment by kaigai** [comment]
Nice catch. It seems to me exactly a bug.
Please wait for deep investigation and fixup.

**Comment by kaigai** [comment]
Fixed at a14982084ea9759c0fc5aedc199f8b949c0bd56d.

Sorry for my late response. I could not have enough time on the last week end due to an influenza.
