### ISSUE TITLE
Won't compile on mac osx 10.11

### ISSUE THREAD

**Issue by rotten** [pg-strom/devel#229]
When I run make on my mac after cloning from github:

```
pg-strom $  make
/Library/Developer/CommandLineTools/usr/bin/make -C src all
Makefile:11: *** missing separator.  Stop.
make: *** [all] Error 2
```

Do I need a different make?

**Comment by kaigai** [comment]
I don't have MacOS environment, so not reproducible...

src/Makefile:11 uses "undefine" command of make.
Is it specific to GNU Make??

**Comment by rotten** [comment]
I just tried gnumake as well - same thing:

```
pg-strom $  gnumake
/Library/Developer/CommandLineTools/usr/bin/gnumake -C src all
Makefile:11: *** missing separator.  Stop.
gnumake: *** [all] Error 2

```

**Comment by rotten** [comment]
I also tried plain make with --debug.  Let me know if there is anything else I might try that would get this to compile.

```
pg-strom $  make --debug
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Updating goal targets....
 File `all' does not exist.
Must remake target `all'.
/Library/Developer/CommandLineTools/usr/bin/make -C src all  --debug=basic
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
Reading makefiles...
Makefile:11: *** missing separator.  Stop.
make: *** [all] Error 2
```

**Comment by ahase** [comment]
Gnu make support 'undefine' directive at 3.82.

http://stackoverflow.com/questions/21347198/environment-variables-cause-makes-undefine-to-fail-windows

**Comment by kaigai** [comment]
Could you try the latest master branch?

I tried to remove "undefine" directive from the Makefile.
It is a hotfix, so I may revise the build chain to support wider platform.

**Comment by kaigai** [comment]
> Gnu make support 'undefine' directive at 3.82.
> http://stackoverflow.com/questions/21347198/environment-variables-cause-makes-undefine-to-fail-windows

Wow, it's exactly new feature. Probably, unavailable on RHEL6.x.

**Comment by kaigai** [comment]
7664e15a1867e705a53ba7abeacc857e760f19d8 revised the build chain entirely.

**Comment by rotten** [comment]
Thanks!  That gets me over that hurdle.

**Comment by mhkeller** [comment]
Did you eventually get this building on macos?

**Comment by kaigai** [comment]
NVIDIA no longer supports CUDA Toolkit on MacOS.
So, we have no way to run PG-Strom here, because we depend on CUDA.
