### ISSUE TITLE
Compile Make problem datastore.c: 119 and 126

### ISSUE THREAD

**Issue by ysergio** [pg-strom/devel#231]
Hello,
I try to install but I have an issue 
Thank you in advance
Best Regards

VERSION = PostgreSQL 9.6devel

root@xxxx:/usr/local/pgsql/pg_strom# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fpic -Werror  -DPGSTROM_VERSION=\"1.0devel\" -DPGSTROM_VERSION_NUM=10000 -DCUDA_INCLUDE_PATH=\"/include\" -DCUDA_LIBRARY_PATH=\"/lib64\" -DCMD_GPUINFO_PATH=\"/usr/local/pgsql/bin/gpuinfo\" -I /include -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o src/datastore.o src/datastore.c
src/datastore.c: In function ‘estimate_num_chunks’:
src/datastore.c:119:31: error: ‘RelOptInfo {aka struct RelOptInfo}’ has no member named ‘reltargetlist’
  int   ncols = list_length(rel->reltargetlist);
                               ^
In file included from /usr/local/pgsql/include/server/postgres.h:47:0,
                 from src/datastore.c:19:
src/datastore.c:126:28: error: ‘RelOptInfo {aka struct RelOptInfo}’ has no member named ‘width’
   htup_size += MAXALIGN(rel->width);
                            ^
/usr/local/pgsql/include/server/c.h:563:17: note: in definition of macro ‘TYPEALIGN’
  (((uintptr_t) (LEN) + ((ALIGNVAL) - 1)) & ~((uintptr_t) ((ALIGNVAL) - 1)))
                 ^
src/datastore.c:126:16: note: in expansion of macro ‘MAXALIGN’
   htup_size += MAXALIGN(rel->width);
                ^
<builtin>: recipe for target 'src/datastore.o' failed
make: *** [src/datastore.o] Error 1
root@xxxx:/usr/local/pgsql/pg_strom#

**Comment by kaigai** [comment]
It is known issue.

Because of drastic leap in v9.6 progress (like parallel execution, upper path optimization, ...), some internal structure gets layout changes.
Right now, we cannot catch up v9.6 code base. Once software quality related works done, we will go into v9.6 code base.

Please use v9.5 instead, until we can support v9.6.

Thanks,

**Comment by ysergio** [comment]
Thank you very much for your reply
Regards

**Comment by ysergio** [comment]
Hello,
I have this problem
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
make: *** [pg_strom.so] Error 1
root@8e42acdcc23e:/home/pg_strom# cd /usr/local/cuda
root@8e42acdcc23e:/usr/local/cuda# ls
LICENSE  README  bin  doc  extras  include  lib64  nvvm  share  src  targets  tools  version.txt
root@8e42acdcc23e:/usr/local/cuda# cd lib64
root@8e42acdcc23e:/usr/local/cuda/lib64# ls
libOpenCL.so         libcufft.so.7.5       libcurand.so.7.5.18    libnppc_static.a        libnvblas.so.7.5
libOpenCL.so.1       libcufft.so.7.5.18    libcurand_static.a     libnppi.so              libnvblas.so.7.5.18
libcublas.so         libcufft_static.a     libcusolver.so         libnppi.so.7.5          libnvrtc-builtins.so
libcublas.so.7.5     libcufftw.so          libcusolver.so.7.5     libnppi.so.7.5.18       libnvrtc-builtins.so.7.5
libcublas.so.7.5.18  libcufftw.so.7.5      libcusolver.so.7.5.18  libnppi_static.a        libnvrtc-builtins.so.7.5.18
libcublas_device.a   libcufftw.so.7.5.18   libcusolver_static.a   libnpps.so              libnvrtc.so
libcublas_static.a   libcufftw_static.a    libcusparse.so         libnpps.so.7.5          libnvrtc.so.7.5
libcudadevrt.a       libcuinj64.so         libcusparse.so.7.5     libnpps.so.7.5.18       libnvrtc.so.7.5.17
libcudart.so         libcuinj64.so.7.5     libcusparse.so.7.5.18  libnpps_static.a        stubs
libcudart.so.7.5     libcuinj64.so.7.5.18  libcusparse_static.a   libnvToolsExt.so
libcudart.so.7.5.18  libculibos.a          libnppc.so             libnvToolsExt.so.1
libcudart_static.a   libcurand.so          libnppc.so.7.5         libnvToolsExt.so.1.0.0
libcufft.so          libcurand.so.7.5      libnppc.so.7.5.18      libnvblas.so

Thank you

**Comment by kaigai** [comment]
Do you already install the nvidia's kernel driver?

If so, I expect /usr/lib64/nvidia contains libcuda*, and /etc/ld.so.conf.d/nvidia-lib64.conf indicates the directly.

**Comment by ysergio** [comment]
Thank you for this information.
I solve and copy in /usr/local/cuda/lib64/
from stubs directory all libxxxxxx.so (in fact from /usr/local/cuda/lib64/stubs).

Maybe the cuda 9.5 release have this stubs directory ?

libcublas.so  libcufft.so   libcurand.so    libcusparse.so  libnppi.so  libnvrtc.so
libcuda.so    libcufftw.so  libcusolver.so  libnppc.so      libnpps.so

Regards
