### ISSUE TITLE
Unable to run on device but in fact is able.

### ISSUE THREAD

**Issue by arron-lyu** [pg-strom/devel#232]
I created two tables and tested a SQL like this
`explain select 
a.02node,
c.xbtcod ,    
a.sbno,
sum(a.value)
from center a           
join relation c 
on a.02node=c.ybtcode
group by 
a.02node,      
c.xbrtcod ,    
a.sbno;`
The data type of 02node,sbno, value, xbtcode, ybtcode are text,text, double,text,text. When I ran this SQL, I found some problems:
- 1. some DEBUG info are printed:

`DEBUG:  Unable to run on device: {AGGREF :aggfnoid 2111 :aggtype 701 ...:location 64}`
`DEBUG:  Unable to run on device: {FUNCEXPR :funcid 401 :funcresulttype 25 ...:location -1}`
`DEBUG:  Unable to run on device: {AGGREF :aggfnoid 2111 :aggtype 701 :...:location 64}`
`DEBUG:  Unable to run on device: {FUNCEXPR :funcid 401 :funcresulttype 25 :...location -1}`
The query plan is 
HashAggregate  (cost=17630367.76..17727814.36 rows=9744660 width=27)
   Group Key: a.dm02node, c.ancbrtcod, a.dm02sbno
   ->  Custom Scan (GpuPreAgg)  (cost=4657250.80..14516182.31 rows=9744660 width=96)
         Reduction: Only Final
         GPU Projection: 02node, sbno, value, xbtcod
         ->  Hash Join  (cost=4653250.80..14311005.64 rows=331936212 width=27)
               Hash Cond: ((c.brtcod)::text = a.dm02node)
               ->  Seq Scan relation c  (cost=0.00..106.48 rows=6848 width=12)
               ->  Hash  (cost=3127594.80..3127594.80 rows=122052480 width=21)
                     ->  Seq Scan on center a  (cost=0.00..3127594.80 rows=122052480 width=21)
(10 rows)

If I blocked the code in line 1303、1304 in src/gpujoin.c, the query plan is :
HashAggregate  (cost=9799507.91..9896954.51 rows=9744660 width=27)
   Group Key: a.dm02node, c.ancbrtcod, a.dm02sbno
   ->  Custom Scan (GpuPreAgg)  (cost=11308.93..6685322.45 rows=9744660 width=96)
         Reduction: Only Final
         GPU Projection: dm02node, dm02sbno, dm02lbalecopy, ancbrtcod
         ->  Custom Scan (GpuJoin) on dpfm02_center a  (cost=7308.93..6480145.79 rows=331936212 width=27)
               GPU Projection: a.dm02node, a.dm02sbno, a.dm02lbalecopy, c.ancbrtcod
               Depth 1: GpuHashJoin, HashKeys: (a.dm02node)
                        JoinQuals: (a.dm02node = (c.brtcod)::text)
                        Nrows (in/out: 271.96%), KDS-Hash (size: 677.20KB, nbatches: 1)
               ->  Seq Scan on cl_brt_relation c  (cost=0.00..106.48 rows=6848 width=12)
(11 rows)

This time, GpuJoin is used, and the results were right, and query time was much shorter. I think the problem is about the function “texteq”( related to "a.02node=c.ybtcode" in SQL)
- 2. One  function(func_oid and func_collid) is inserted to _devfunc_info_slot_ many times.

For example, the first time to look up a function(func_oid = 67, func_collid = 100), "func_oid = 67, func_collid = 0" is inserted to devfunc_info_slot, because has_collation = false, func_collid is setted to InvalidOid. the second time, the same function  is looked up, now, in line 1220 in src/codegen.c, entry->func_oid == func_oid, entry->func_collid **!=** func_collid, so, the same function is inserted to _devfunc_info_slot_ again and again, and "func_collid"  is also setted to InvalidOid. So, there many "func_oid = 67, func_collid = 0“ in the _devfunc_info_slot_. Is this a bug?

**Comment by kaigai** [comment]
Hello,

```
DEBUG: Unable to run on device: {FUNCEXPR :funcid 401 :funcresulttype 25 ...:location -1}
```
This debug message said, type cast from bpchar to text are not supported.
Also, EXPLAIN output says c.brtcod is something different from the text data type.
```
Hash Cond: ((c.brtcod)::text = a.dm02node)
```
I doubt you use bpchar(n) data type instead of the text.
Both of data types are varlena, so very similar but bpchar(n) has padding space on
the tail. Thus, we cannot compare them without valid type casting.
Please don't remove checks to ensure valid results.

> So, there many "func_oid = 67, func_collid = 0“ in the devfunc_info_slot. Is this a bug?

You are right. This logic checks func_collid too early. Thanks,
