### ISSUE TITLE
pg_storm will cause assert fault when  do join query .

### ISSUE THREAD

**Issue by jarwin123** [pg-strom/devel#234]
postgres=# \d t1
      Table "public.t1"
 Column |  Type   | Modifiers 
--------+---------+-----------
 c1     | integer | 
 c2     | integer | 

postgres=# \d t2
      Table "public.t2"
 Column |  Type   | Modifiers 
--------+---------+-----------
 c1     | integer | 
 c2     | integer | 

postgres=# \d t3
      Table "public.t3"
 Column |  Type   | Modifiers 
--------+---------+-----------
 c1     | integer | 
 c2     | integer | 

postgres=# explain (analyze,verbose,costs,buffers,timing) select count(*) from t1;
                                                               QUERY PLAN                                                               
----------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=169247.71..169247.72 rows=1 width=0) (actual time=1225.859..1225.859 rows=1 loops=1)
   Output: pgstrom.count((pgstrom.nrows()))
   Buffers: shared hit=30 read=44248
   ->  Custom Scan (GpuPreAgg) on public.t1  (cost=4000.00..149812.83 rows=256 width=4) (actual time=1120.451..1225.848 rows=1 loops=1)
         Output: pgstrom.nrows()
         Reduction: NoGroup
         GPU Projection: t1.c1, t1.c2
         Outer Scan: public.t1 (actual time=9.124..392.365 rows=10000000 loops=1)
                     buffers: shared hit=30 read=44248
         Logic Parameter: SafetyLimit: 2147483647, KeyDistSalt: 256
         Buffers: shared hit=30 read=44248
 Planning time: 6.583 ms
 Execution time: 1389.801 ms
(13 rows)

postgres=# explain (analyze,verbose,costs,buffers,timing) select count(*) from t1,t2,t3 where t1.c1=t2.c1 and t2.c1=t3.c1;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
postgres=# 

TRAP: FailedAssertion("!(jscale[i].window_base + jscale[i].window_size == nitems)", File: "src/gpujoin.c", Line: 5548)
LOG:  server process (PID 10729) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: explain (analyze,verbose,costs,buffers,timing) select count(*) from t1,t2,t3 where t1.c1=t2.c1 and t2.c1=t3.c1;
LOG:  terminating any other active server processes

**Comment by kaigai** [comment]
Thanks for the report.

GpuJoin's window_base/size were incorrectly calculated on the gpujoin_try_next_window().
Fixed at ffe101556b64f4f083ed80b82c72b21b40aaed43

**Comment by jarwin123** [comment]
sorry, after i update source,this problem cause:

postgres=# explain (analyze,verbose,costs,buffers,timing) select count() from t1,t2,t3 where t1.c1=t2.c1 and t2.c1=t3.c1;
ERROR: failed on cuMemAllocHost: CUDA_ERROR_OUT_OF_MEMORY - out of memory
and log is:
ERROR: failed on cuMemAllocHost: CUDA_ERROR_OUT_OF_MEMORY - out of memory
STATEMENT: explain (analyze,verbose,costs,buffers,timing) select count() from t1,t2,t3 where t1.c1=t2.c1 and t2.c1=t3.c1;

i exec command:
./gpuinfo

CUDA Runtime version: 8.0.0
NVIDIA Driver version: 361.42
Number of devices: 1

Device Identifier: 0
Device Name: GeForce GTX 960M
Global memory size: 2047MB
Maximum number of threads per block: 1024
Maximum block dimension X: 1024
Maximum block dimension Y: 1024
Maximum block dimension Z: 64
Maximum grid dimension X: 2147483647
Maximum grid dimension Y: 65535
Maximum grid dimension Z: 65535
Maximum shared memory available per block in bytes: 49152KB
Memory available on device for constant variables: 65536bytes
Warp size in threads: 32
Maximum number of 32-bit registers available per block: 65536
Typical clock frequency in kilohertz: 1176000KHZ
Number of multiprocessors on device: 5
Specifies whether there is a run time limit on kernels: 1
Device is integrated with host memory: false
Device can map host memory into CUDA address space: true
Compute mode (See CUcomputemode for details): default
Device can possibly execute multiple kernels concurrently: true
Device has ECC support enabled: false
PCI bus ID of the device: 1
PCI device ID of the device: 0
Device is using TCC driver model: false
Peak memory clock frequency in kilohertz: 2505000KHZ
Global memory bus width in bits: 128
Size of L2 cache in bytes: 2097152bytes
Maximum resident threads per multiprocessor: 2048
Number of asynchronous engines: 1
Device shares a unified address space with the host: true
Major compute capability version number: 5
Minor compute capability version number: 0
Device supports stream priorities: true
Device supports caching globals in L1: false
Device supports caching locals in L1: true
Maximum shared memory available per multiprocessor: 65536bytes
Maximum number of 32bit registers per multiprocessor: 65536
Device can allocate managed memory on this system: true
Device is on a multi-GPU board: false
Unique id for a group of devices on the same multi-GPU board: 0
