### ISSUE TITLE
error when run nvrtcCompileProgram on older GPU

### ISSUE THREAD

**Issue by kensouryou** [pg-strom/devel#235]
Hi, all

Need help.

OS: CentOS 6.7
DB: PostgreSQL 9.5.3

startup message
> LOG:  CUDA Runtime version: 7.5.0
> LOG:  NVIDIA driver version: 352.39
> LOG:  GPU0 GeForce GT 440 (96 CUDA cores, 1620MHz), L2 128KB, RAM 1023MB (128bits, 900MHz), capability 2.1
> LOG:  NVRTC - CUDA Runtime Compilation vertion 7.5

It is an older GPU card and only has computing capability 2.1. I modified some code in cuda_control.c make the PG-Strom can run. But I send query like SELECT sum(aid) ... PG reported:

> ERROR:  build: failed
> 	pg_strom(2413): error: identifier "cudaGetDevice" is undefined
> 	
> 	pg_strom(2417): error: identifier "cudaDeviceGetAttribute" is undefined
> ...
> 	27 errors detected in the compilation of "pg_strom".
> 	
> 	source: /opt/PostgreSQL/9.5/bin/../data/base/pgsql_tmp/pgsql_tmp_strom_1661.0.gpu

Should I order a new card which supported computing capability 3.5?

Thank you.

**Comment by kaigai** [comment]
GPUs older than CC3.5 has no hope to run PG-Strom.

The main reason is dynamic parallelism which is newly supported at CC3.5, and most of GPU-side implementation of PG-Strom depends on this functionality. Some device run-time APIs, like cudaDeviceGetAttribute, are only valid on CC3.5 or later.

Best regards,

**Comment by kensouryou** [comment]
Got it.

Thank you.
