### ISSUE TITLE
pg_storm  cuMemAllocHost: CUDA_ERROR_OUT_OF_MEMORY  out of memory

### ISSUE THREAD

**Issue by jarwin123** [pg-strom/devel#236]
postgres=# \d t1
Table "public.t1"
Column | Type | Modifiers
--------+---------+-----------
c1 | integer |
c2 | integer |

postgres=# \d t2
Table "public.t2"
Column | Type | Modifiers
--------+---------+-----------
c1 | integer |
c2 | integer |

postgres=# \d t3
Table "public.t3"
Column | Type | Modifiers
--------+---------+-----------
c1 | integer |
c2 | integer |

postgres=# select count(*) from t1;
##   count   

 10000000
(1 row)

postgres=# select count(*) from t2;
##   count   

 10000000
(1 row)

postgres=# select count(*) from t3;
##   count   

 10000000
(1 row)

sorry, after i update source,this problem cause:

postgres=# explain (analyze,verbose,costs,buffers,timing) select count(*) from t1 natural join t2;
##                                                                        QUERY PLAN                                                                        

 Aggregate  (cost=764519.92..764519.93 rows=1 width=0) (actual time=4737.179..4737.179 rows=1 loops=1)
   Output: pgstrom.count((pgstrom.nrows()))
   Buffers: shared hit=60 read=132744
   ->  Custom Scan (GpuPreAgg)  (cost=218591.08..745085.04 rows=256 width=4) (actual time=4490.586..4737.173 rows=1 loops=1)
         Output: pgstrom.nrows()
         Reduction: NoGroup
         Logic Parameter: SafetyLimit: 2147483647, KeyDistSalt: 256
         Extra: outer-bulk-exec
         Buffers: shared hit=60 read=132744
         ->  Custom Scan (GpuJoin) on public.t1  (cost=214591.08..739519.98 rows=9999977 width=0) (actual time=2973.686..4475.032 rows=10000000 loops=1)
               GPU Projection: 
               Outer Scan: public.t1 (actual time=10.617..253.262 rows=10000000 loops=2)
                           buffers: shared hit=60 read=88496
               Depth 1: GpuHashJoin, HashKeys: (t1.c1, t1.c2)
                        JoinQuals: ((t1.c1 = t2.c1) AND (t1.c2 = t2.c2))
                        Nrows (in:28785864 out:10000000, 34.74% planned 100.00%)
                        KDS-Hash (size: 340.99MB planned 290.08MB, nbatches: 2 planned 3)
               Inner Buffer: (340.99MB, 340.99MB), DMA nums: 5, size: 1704.96MB
               Extra: bulk-exec-support, row-format
               Buffers: shared hit=60 read=132744
               ->  Seq Scan on public.t2  (cost=0.00..144247.77 rows=9999977 width=8) (actual time=0.014..686.735 rows=10000000 loops=1)
                     Output: t2.c1, t2.c2
                     Buffers: shared read=44248
 Planning time: 12.708 ms
 Execution time: 5108.508 ms
(25 rows)

postgres=# explain (analyze,verbose,costs,buffers,timing) select count(*) from t1,t2,t3 where t1.c1=t2.c1 and t2.c1=t3.c1;
ERROR:  failed on cuMemAllocHost: CUDA_ERROR_OUT_OF_MEMORY - out of memory
postgres=# 

i exec command:
./gpuinfo

CUDA Runtime version: 8.0.0
NVIDIA Driver version: 361.42
Number of devices: 1

Device Identifier: 0
Device Name: GeForce GTX 960M
Global memory size: 2047MB
Maximum number of threads per block: 1024
Maximum block dimension X: 1024
Maximum block dimension Y: 1024
Maximum block dimension Z: 64
Maximum grid dimension X: 2147483647
Maximum grid dimension Y: 65535
Maximum grid dimension Z: 65535
Maximum shared memory available per block in bytes: 49152KB
Memory available on device for constant variables: 65536bytes
Warp size in threads: 32
Maximum number of 32-bit registers available per block: 65536
Typical clock frequency in kilohertz: 1176000KHZ
Number of multiprocessors on device: 5
Specifies whether there is a run time limit on kernels: 1
Device is integrated with host memory: false
Device can map host memory into CUDA address space: true
Compute mode (See CUcomputemode for details): default
Device can possibly execute multiple kernels concurrently: true
Device has ECC support enabled: false
PCI bus ID of the device: 1
PCI device ID of the device: 0
Device is using TCC driver model: false
Peak memory clock frequency in kilohertz: 2505000KHZ
Global memory bus width in bits: 128
Size of L2 cache in bytes: 2097152bytes
Maximum resident threads per multiprocessor: 2048
Number of asynchronous engines: 1
Device shares a unified address space with the host: true
Major compute capability version number: 5
Minor compute capability version number: 0
Device supports stream priorities: true
Device supports caching globals in L1: false
Device supports caching locals in L1: true
Maximum shared memory available per multiprocessor: 65536bytes
Maximum number of 32bit registers per multiprocessor: 65536
Device can allocate managed memory on this system: true
Device is on a multi-GPU board: false
Unique id for a group of devices on the same multi-GPU board: 0

**Comment by kaigai** [comment]
cuMemAllocHost() is a function to allocate host memory rather than device memory.
I doubt your system has small amount of memory, likely a few gigabytes.

Could you show me the result of ```free -m```?

**Comment by jarwin123** [comment]
free -m
              total        used        free      shared  buff/cache   available
Mem:           7873        1311        5629          33         932        6444
Swap:          3573         169        3404

**Comment by jarwin123** [comment]
My laptop memory have 8G.

**Comment by kaigai** [comment]
Could you try with smaller ```pg_strom.max_async_tasks``` configuration?
It may be a too aggressive asynchronous situation, or fundamentally physical memory is less than necessity.
If ```pg_strom.max_async_tasks``` does not work, please turn of GpuPreAgg; by ```SET pg_strom.enable_gpupreagg=off```. This logic tends to consume much memory.
