### ISSUE TITLE
FATAL:  No supported CUDA devices, PG-Strom was disabled

### ISSUE THREAD

**Issue by skywalkerytx** [pg-strom/devel#237]
hw:
nvidia card: GTX 970
RAM 64GB ddr4 2133
env:
Ubuntu 16.04 LTS
cuda installed through apt repo

cuda test passed with `tensorflow`

log:

`LOG:  PG-Strom version 1.0devel built for PostgreSQL 9.5`

`sh: 1: /usr/local/pgsql/bin/gpuinfo: not found`

`FATAL:  No supported CUDA devices, PG-Strom was disabled`

**Comment by kaigai** [comment]
How did you install the PG-Strom extension?

I doubt ```make install``` referenced the ```pg_config``` installed by the distribution; like RHEL.
Please ensure the ```PATH``` environment variable used on ```make```.

**Comment by skywalkerytx** [comment]
`which pg_config` works, only one pgsql on my machine

about $PATH I did:

`export PATH=/usr/local/pgsql/bin:$PATH`

and When using `sudo make install`

`sudo make install`
`/bin/sh: 1: rpm: not found`
`/bin/sh: 1: rpm: not found`
`/bin/sh: 1: --version: not found`
`/bin/sh: 1: rpm: not found`
`make: --bindir: Command not found`
`/bin/sh: 0: Illegal option --`
`/bin/sh: 1: test: -ge: unexpected operator`
`make: --pgxs: Command not found`
`make: *** No rule to make target 'install'.  Stop.` 

so I just do `make` and edited `postgresql.conf` to

`shared_preload_libraries = '/home/nova/pg_strom/pg_strom.so'`

**Comment by kaigai** [comment]
Seems to me strange.

This message implies ```which pg_config``` couldn't find the command.
```
make: --pgxs: Command not found
```

Does the command below work?
```
make PG_CONFIG=/usr/local/pgsql/bin/pg_config
```

Also, I'm a little bit surprise at ```rpm``` command was not installed.
It needs a few revise of Makefile.

**Comment by skywalkerytx** [comment]
`sudo make PG_CONFIG=/usr/local/pgsql/bin/pg_config CUDA_PATH=/usr`

`sudo make install PG_CONFIG=/usr/local/pgsql/bin/pg_config CUDA_PATH=/usr`

pg_strom installed and `pg_ctl` shows that it works.

now do I need to edit `shared_preload_libraries` in `postgresql.conf` again? I suppose it is still using `~/pg_strom/pg_strom.so`

**Comment by kaigai** [comment]
As long as ```shared_preload_libraries``` points to the correct binary module, you don't need to edit it again. Please restart the PostgreSQL server, and then run ```CREATE EXTENSION pg_strom```.

BTW, what distribution do you use? I'm not sure why ```rpm``` command is missing.

**Comment by skywalkerytx** [comment]
I'm using a newly installed Kubuntu 16.04.1 LTS ( installed few hours ago,fully up-to-date)

rpm is in repo, `apt-get install rpm` solved the problem.

**Comment by skywalkerytx** [comment]
one more thing for people who reached here:

cuda 7.5 in ubuntu 16.04 don't have `$CUDA_HOME/lib64` which normal cuda installation has so it will cause error message following:

`psql:b.sql:7: ERROR:  (cuda_program.c:530, link_cuda_libraries) failed on cuLinkAddFile("/usr/lib64/libcudadevrt.a"): CUDA_ERROR_FILE_NOT_FOUND - file not found`

solution: `ln -s /usr/lib/x86_64-linux-gnu /usr/lib64` , then re-compile pg_strom, and restart server.

**Comment by kaigai** [comment]
Did you installed CUDA to the default path? (```/usr/local/cuda```)

Unfortunately, ```Makefile``` have no reliable way to find out the CUDA installation path, so it assumes this default directory.
If you installed CUDA with own configuration, please run ```make CUDA_PATH=/path/to/your/cuda/installation```

**Comment by skywalkerytx** [comment]
It is a system-specific issue for ubuntu-like system, default path of CUDA is changed by community in their repo, and inner structure of CUDA folder is also changed by them (not NVIDIA).

so I add some additional comment just to solve that part.
