### ISSUE TITLE
Where can download sample SQL?

### ISSUE THREAD

**Issue by kensouryou** [pg-strom/devel#239]
Mr.Kaigai

Where can download SQLs and sample data mentioned in document?
http://strom.kaigai.gr.jp/tutrial.html#tutrial-basic-operations

like
EXPLAIN
           SELECT cat, avg(ax) FROM t0 NATURAL JOIN t1 NATURAL JOIN t2 GROUP BY cat;
                                    QUERY PLAN

Thank you.
Quan

**Comment by kaigai** [comment]
Please see test/testdb.sql of the master branch.
It constructs one 100M rows table and 9 of 100K rows table.

**Comment by kensouryou** [comment]
Found it.
Thank you.
