### ISSUE TITLE
corr(), covar_pop(), covar_samp() fail with 'identifier "temp_float8_v" is undefined'

### ISSUE THREAD

**Issue by s34gull** [pg-strom/devel#242]
Tesla K40m, CUDA 7.5,  Driver Version: 361.42 

When running `where_gpa.sql`, the dynamically generated GPU code in /var/opt/postgres/data/base/pgsql_tmp/pgsql_tmp_strom_443.0.gpu is failing to run 

> var_pop        
> -----------------------
> 380478214898.47182667
> (1 row)

> var_samp        
> -----------------------
> 380877457516.41355996
> (1 row)
> psql:where_gpa.sql:38:

> ERROR:  build: failed
>  pg_strom(7649): error: identifier "temp_float8_v" is undefined

>  pg_strom(7664): error: identifier "temp_float8_v" is undefined

>  pg_strom(7681): error: identifier "temp_float8_v" is undefined

>  pg_strom(7696): error: identifier "temp_float8_v" is undefined

>  pg_strom(7713): error: identifier "temp_float8_v" is undefined

>  5 errors detected in the compilation of "pg_strom".`

Basic functions seem to work properly (avg, max, min, etc.)

**Comment by kaigai** [comment]
Thanks for your report.

815e1c60e48a018cefa934c16ee888513b74e5a9 fixed it.
It looks to me I didn't update the code generator around aggregate function with two arguments when I reworked the gpupreagg.c.
