### ISSUE TITLE
Why does pg-strom require device capability of 3.5 or higher?

### ISSUE THREAD

**Issue by jimwu88** [pg-strom/devel#243]
I installed pg-strom with postgresql 9.5. When I restart the server, it shows that my GPU device below is not supported. I googled it and looks like pg-strom requires device capability to be 3.5 or higher. What are the main reasons?

GPU0 NVS 4200M (48 CUDA cores, 1480MHz), L2 64KB, RAM 511MB (64bits, 800MHz), capability 2.1

**Comment by kaigai** [comment]
The feature of Dynamic Parallelism; supported by CC3.5 or later with NVIDIA's product.

Reduction of interruption by CPU is a key of performance.
On the other hands, some of SQL workloads are fundamentally difficult to estimate an optimal problem size preliminary. For example, we cannot know exact number of rows to be generated by tables join before execution (unless proper relationship like PK/FK is not set). Especially, when we process multiple tables join in a single GPU kernel call, the problem size in (k+1) depth is determined by the result in k depth, however, we never know when GPU kernel is launched.
Dynamic Parallelism allows to launch GPU kernel with appropriate problem size by GPU kernel.
It allows to determine the size of (k+1) depth according to the result in k-depth, without interruption of CPU. It is a great advantage and requires fundamentally different logic from CPU-based adjustment.
So, we determined to drop support of CC3.0 or older.

P.S, It looks to me your GPU is a bit old and less computing power than modern CPUs. Even if PG-Strom can work on, it will be hard to get performance advantage.

Thanks,

**Comment by jimwu88** [comment]
Hi Kaigai,

Thanks for your quick reply! Is there a low-cost GPU card with capability 3.5 or newer that you can recommend? Thanks!

**Comment by kaigai** [comment]
I never recommend it, but I confirmed GTX750Ti (CC5.0) was working by myself. Its computing power is poor, but sufficient functionality to run.
I usually use GTX980 (CC5.2) for my development. Its successor model (GTX1080) is already in-market, so you may be able to get this card cheaper than my case.

**Comment by jimwu88** [comment]
Thanks. I am getting a GTX1020.
