### ISSUE TITLE
PG Strom library not loading on Ubuntu 14.04, PG 9.5, and AWS P2 NVIDIA AMI setup

### ISSUE THREAD

**Issue by triptimahakul** [pg-strom/devel#251]
I am trying to setup PGStrom following the wiki page on my AWS P2 NVIDIA AMI.
Every thing looks ok but not seem to startup Postgres.

:/usr/local/cuda-7.5/samples/1_Utilities/deviceQuery$ lspci | grep -i nvidia
00:1e.0 3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
:/usr/local/cuda-7.5/samples/1_Utilities/deviceQuery$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.99  Mon Jul  4 23:52:14 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

:/usr/local/cuda-7.5/samples/1_Utilities/deviceQuery$ ./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Tesla K80"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.7
  Total amount of global memory:                 11520 MBytes (12079136768 bytes)
  (13) Multiprocessors, (192) CUDA Cores/MP:     2496 CUDA Cores
  GPU Max Clock rate:                            824 MHz (0.82 GHz)
  Memory Clock rate:                             2505 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 30
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = Tesla K80
Result = PASS

But I am failing to bring up Postgres on the instance.
It is throwing this error
 FATAL:  could not load library "/usr/lib/postgresql/9.5/lib/pg_strom.so": /usr/lib/postgresql/9.5/lib/pg_strom.so: undefined symbol: set_latch_on_sigusr1

What am i missing?

**Comment by kaigai** [comment]
```set_latch_on_sigusr1``` is used at the code below:
```
static bool
waitfor_ready_tasks(GpuTaskState *gts)
{
#if PG_VERSION_NUM < 90600
    /*
     * NOTE: db0f6cad4884bd4c835156d3a720d9a79dbd63a9 of PostgreSQL
     * removed 'set_latch_on_sigusr1' because of less performance
     * benefit, so v9.6 or later don't need to save and restore the
     * status.
     */
    bool    save_set_latch_on_sigusr1 = set_latch_on_sigusr1;
    bool    status;

    set_latch_on_sigusr1 = true;
    PG_TRY();
    {
        status = __waitfor_ready_tasks(gts);
    }
    PG_CATCH();
    {
        set_latch_on_sigusr1 = save_set_latch_on_sigusr1;
        PG_RE_THROW();
    }
    PG_END_TRY();
    set_latch_on_sigusr1 = save_set_latch_on_sigusr1;

    return status;
#else
    return __waitfor_ready_tasks(gts);
#endif
}
```
I want to know whether you really build the PG-Strom (STABLE_v1 branch) towards
PostgreSQL v9.5.x.
Could you show me the result of ```pg_config``` when you build PG-Strom?
And, please ensure the PostgreSQL binary is really v9.5.x.

**Comment by triptimahakul** [comment]
I built it twice once with the URL in wiki and second with the STABLE_v1_branch and both times i get the same error. This is how the pg_config looks
pg_config
BINDIR = /usr/lib/postgresql/9.5/bin
DOCDIR = /usr/share/doc/postgresql-doc-9.5
HTMLDIR = /usr/share/doc/postgresql-doc-9.5
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/9.5/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/9.5/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/9.5/man
SHAREDIR = /usr/share/postgresql/9.5
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/9.5/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' '--with-tclconfig=/usr/lib/x86_64-linux-gnu/tcl8.6' '--with-includes=/usr/include/tcl8.6' 'PYTHON=/usr/bin/python' '--mandir=/usr/share/postgresql/9.5/man' '--docdir=/usr/share/doc/postgresql-doc-9.5' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/9.5' '--bindir=/usr/lib/postgresql/9.5/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5' '--with-krb5' '--with-gssapi' '--with-ldap' '--with-selinux' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'
CC = gcc
CPPFLAGS = -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/tcl8.6
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.5.5

As you can see, version is indeed Postgresql 9.5

**Comment by kaigai** [comment]
Hmm... It seems to me quite strange. This variable always exists regardless of the configuration.

Did you build PostgreSQL from the source by yourself? Or, used pre-built package?
If you used AMI, please tell me the identifier of the AMI you use.

Also, could you confirm the ```pg_config``` above is really identical command which you used on
the build of PG-Strom? I saw somebody build PG-Strom using different version of pg_config due
to the PATH environment variable.

**Comment by triptimahakul** [comment]
You were right. It was the way that i built PostgreSQL that was the problem.
I also had two versions of pg_config.

I stood up a fresh instance and installed PostgreSQL dev 9.5 ,made sure pg_config pointed to that.
After that i could restart the database.

postgres@ip-xxx-xx-xx-xxx:~$ pg_ctl -D /var/lib/postgresql/9.5/main start
server starting
postgres@ip-xxx-xx-xx-xxx:~$ 2016-11-26 16:58:23 UTC [19401-1] LOG:  PG-Strom version 1.0 built for PostgreSQL 9.5
2016-11-26 16:58:23 UTC [19401-2] LOG:  CUDA Runtime version: 7.5.0
2016-11-26 16:58:23 UTC [19401-3] LOG:  NVIDIA driver version: 352.99
2016-11-26 16:58:23 UTC [19401-4] LOG:  GPU0 Tesla K80 (2496 CUDA cores, 823MHz), L2 1536KB, RAM 11519MB (384bits, 2505MHz), capability 3.7
2016-11-26 16:58:23 UTC [19401-5] LOG:  NVRTC - CUDA Runtime Compilation vertion 7.5
2016-11-26 16:58:23 UTC [19404-1] LOG:  database system was shut down at 2016-11-26 16:56:01 UTC
2016-11-26 16:58:23 UTC [19404-2] LOG:  MultiXact member wraparound protections are now enabled
2016-11-26 16:58:23 UTC [19408-1] LOG:  autovacuum launcher started
2016-11-26 16:58:23 UTC [19401-6] LOG:  database system is ready to accept connections

postgres@ip-xxx-xx-xx-xxx:~$ psql -l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)

postgres@ip-xxx-xx-xx-xxx:~$ psql
psql (9.5.5)
Type "help" for help.

postgres=# 

Thanks so much for your valuable pointers!
