### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by ValliAnns** [pg-strom/devel#252]
I tried to do ./configure --enable-debug. But when I tried, no configuration file found. Only makefile is there. How can I give --enable-debug now?

**Comment by kaigai** [comment]
PG-Strom does not use own ./configure script, because it needs strictly identical configuration with the target PostgreSQL. So, it references the configuration of PostgreSQL build. Please confirm the pg_config command output.

**Comment by kaigai** [comment]
My answer was not direct to your question.

Please build your target PostgreSQL with ./configure --enable-debug.
Or, put ```Makefile.custom``` that contains ```PGSTROM_FLAGS_CUSTOM := -g``` for equivalent effect.

**Comment by ValliAnns** [comment]
Yeah okay

Output of pg_config: 

```
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--enable-debug' 'CC=/usr/bin/gcc' 'CXX=/usr/bin/g++' 'CFLAGS=-O0 -g3 -gdwarf-2' 'CXXFLAGS=-O0 -g3 -gdwarf-2'
CC = /usr/bin/gcc
CPPFLAGS = -D_GNU_SOURCE
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O0 -g3 -gdwarf-2
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lz -lreadline -lrt -lcrypt -ldl -lm 
VERSION = PostgreSQL 9.5.4
```

**Comment by ValliAnns** [comment]
How to link pg_strom with postgres?
I did install postgres and pg_strom using make install. But what are the linking steps?
