### ISSUE TITLE
Device NOT SUPPORTED

### ISSUE THREAD

**Issue by svireli** [pg-strom/devel#262]
Hello, i have a workstation with Nvidia Quadro K600. On official website is written that it supports cuda but when i'm starting pgsql it logs this:

`LOG:  CUDA Runtime version: 8.0.0`
`LOG:  NVIDIA driver version: 367.57`
`LOG:  GPU0 Quadro K600 (1 SMs, 875MHz), L2 256KB, RAM 980MB (128bits, 891MHz), capability 3.0, NOT SUPPORTED`
`FATAL:  No supported CUDA devices, PG-Strom was disabled`

Can someone explaint this?

**Comment by kaigai** [comment]
https://github.com/pg-strom/devel/wiki/GPU-Availability-Matrix

Sorry, your device's compute capability is not sufficient, thus, PG-Strom does not support it.
(CC=3.5 or later is required)
If you get an impression as if your device is supported, please tell me which description is problematic.
I'll fix it.

**Comment by svireli** [comment]
Thank you very much.
