### ISSUE TITLE
In ver 2.0 (master), error occurs when running (postgresql 9.6.2)

### ISSUE THREAD

**Issue by xuxilei** [pg-strom/devel#267]
[postgres@localhost ~]$ postgres -D ~/pgsql/data1 &

[1] 11618

[postgres@localhost ~]$ LOG:  PG-Strom version 2.0devel built for PostgreSQL 9.6

LOG:  PG-Strom: GPU0 GeForce GTX 1080 (2560 CUDA cores; 1809MHz, L2 2048kB), RAM 7.92GB (256bits, 4.77GHz), CC 6.1

LOG:  PG-Strom: GPU1 GeForce GTX 1080 (2560 CUDA cores; 1809MHz, L2 2048kB), RAM 7.92GB (256bits, 4.77GHz), CC 6.1

LOG:  NVRTC - CUDA Runtime Compilation vertion 8.0

cc1: error: /root/postgresql-9.6.2/src/include/: Permission denied

FATAL:  failed on nvcc (/usr/local/cuda/bin/nvcc  --relocatable-device-code=true --gpu-architecture=sm_61 -DPGSTROM_BUILD_WRAPPER --device-c /tmp/plsusN.cu -o /tmp/plsusN.cu.sm_61.o)

LOG:  database system is shut down

 

[1]+  Exit 1                  postgres -D ~/pgsql/data1

[postgres@localhost ~]$cat  .bash_profile 
# .bash_profile 

# Get the aliases and functions

if [ -f ~/.bashrc ]; then

         . ~/.bashrc

fi

 

# User specific environment and startup programs

 

PATH=$PATH:$HOME/bin:/usr/local/cuda-8.0/bin:/usr/local/pgsql/bin

 

export PATH

LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64

export LD_LIBRARY_PATH

C_INCLUDE_PATH=/root/postgresql-9.6.2/src/include/

export C_INCLUDE_PATH

**Comment by kaigai** [comment]
Usually /root is restricted to access by unprivileged users.

Could you install PostgreSQL somewhere your user/group can access?
I usually install PostgreSQL v9.6 on /usr/local/pgsql-9.6 and allows everyone "r-x" access.

**Comment by xuxilei** [comment]
but it running OK  when GPU is except

**Comment by kaigai** [comment]
It looks to me your trouble is lead by compile of wrapper library which shall be constructed on the startup time, and it references the header files of PostgreSQL.
It shall not happen unless PG-Strom is not enabled.

So, it is quite natural your installation landscape does not raise an error because PostgreSQL does not have such a feature to reference header files.
