### ISSUE TITLE
scale-out of postgres-xl: can it does GPU?

### ISSUE THREAD

**Issue by xuxilei** [pg-strom/devel#268]
http://www.postgres-xl.org/

**Comment by kaigai** [comment]
I also want to know. :-)

As an aside, Citus tweeted this in the past.
https://twitter.com/citusdata/status/664566603183316992

It should be possible, if these scale-out solution run vanilla PostgreSQL in the worker node and master node passes "partial" queries in the form not yet planned.
Our team plan to evaluate CitusDB + PG-Strom within several months, but not yet.
