### ISSUE TITLE
Plan ahead for integrating with Postgres' JIT

### ISSUE THREAD

**Issue by thedrow** [pg-strom/devel#271]
There is currently work to provide JIT compilation for SQL queries. You can find it [here](https://github.com/ispras/postgres). 
In case it will be merged what are the effects on PG-storm? How will we integrate with the JIT?

**Comment by kaigai** [comment]
PG-Strom's JIT already have execution of expression on GPU side, using a functionality of CustomScan.

https://www.slideshare.net/kaigai/20160407gtc2016pgsqlinplace
p.27 and p.28 introduces the feature of GpuProjection as a part of GpuJoin.

Briefly, CPU references the result of expression calculated in GPU.
