### ISSUE TITLE
Support postgresql 9.6

### ISSUE THREAD

**Issue by PRijnbeek** [pg-strom/devel#272]
Any updates on supporting 9.6?

"error Base PostgreSQL version is too NEW for this PG-Strom code"

i see a branch what is its status?

**Comment by skywalkerytx** [comment]
default branch is stable_v1, which is bit old.

u can try master

2017年5月2日 上午5:12，"Peter Rijnbeek" <notifications@github.com>写道：

**Comment by kaigai** [comment]
Yes, master branch is under active development, but for v9.6; including CPU+GPU hybrid parallel.
