### ISSUE TITLE
(JP) データがnullの場合に、sum()の結果が0となる。

### ISSUE THREAD

**Issue by ahase** [pg-strom/devel#93]
値が存在しないデータに対して、「select sum(x) from test;」を実行すると、nullが出力されるべき結果に0が出力される。smallintとinteger, smallserial, serial型のデータ型で問題が発生する。

----------------------------------------------------------------------------------------------------------
<pre>
postgres=# \d test
     Table "public.test"
 Column |  Type   | Modifiers
--------+---------+-----------
 key    | integer |
 x      | integer |

postgres=# select * from test;
 key | x
-----+---
   1 |
(1 row)

(reverse-i-search)`sum': select ^Cm(x) from test;
postgres=# set pg_strom.enabled=on;
SET
postgres=# select sum(x) from test;
 sum
-----
   0
(1 row)

postgres=# set pg_strom.enabled=off;
SET
postgres=# select sum(x) from test;
 sum
-----

(1 row)
</pre>

**Comment by kaigai** [comment]
7c9f647ce3efa5573ea14caa102ee8d2a31e1769 にて修正。
